<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Exclude>[EricksonLopez.DomainPrimitives.Generators]EricksonLopez.DomainPrimitives.Generators.Models.*,[EricksonLopez.DomainPrimitives.Generators]EricksonLopez.DomainPrimitives.Generators.GeneratorHelpers</Exclude>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies.Net80" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives.Generators\EricksonLopez.DomainPrimitives.Generators.csproj" />
  </ItemGroup>
</Project>
