<Project>
  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Generator')) Or $(MSBuildProjectName.Contains('Analyzer')) Or $(MSBuildProjectName.Contains('Tests')) Or $(MSBuildProjectName.Contains('Benchmarks'))">
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsRoslynComponent)' == 'true'">
    <IncludeSymbols>false</IncludeSymbols>
  </PropertyGroup>
</Project>
