//HintName: AddressDapperExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using TestNamespace;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

/// <summary>
/// Dapper extensions for the Address Value Object.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class AddressDapperExtensions
{
    /// <summary>
    /// Adds the properties of the Address to the DynamicParameters.
    /// </summary>
    public static void AddParameters(this DynamicParameters parameters, Address value, string prefix = "")
    {
        parameters.Add($"{prefix}Street", value.Street);
        parameters.Add($"{prefix}City", value.City);
        parameters.Add($"{prefix}ZipCode", value.ZipCode);
    }

    /// <summary>
    /// Parses a Address from an IDataRecord.
    /// </summary>
    public static Address ParseValueObject(this IDataRecord record, string prefix = "")
    {
        var idx_Street = record.GetOrdinal($"{prefix}Street");
        var val_Street = record.IsDBNull(idx_Street) ? default : (string)record.GetValue(idx_Street);
        var idx_City = record.GetOrdinal($"{prefix}City");
        var val_City = record.IsDBNull(idx_City) ? default : (string)record.GetValue(idx_City);
        var idx_ZipCode = record.GetOrdinal($"{prefix}ZipCode");
        var val_ZipCode = record.IsDBNull(idx_ZipCode) ? default : (string)record.GetValue(idx_ZipCode);
        return Address.Create(val_Street!, val_City!, val_ZipCode!);
    }
}
