//HintName: TestNamespace_OrderIdTypeHandler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using TestNamespace;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class OrderIdTypeHandler : SqlMapper.TypeHandler<global::TestNamespace.OrderId>
{
    public override void SetValue(IDbDataParameter parameter, global::TestNamespace.OrderId value)
    {
        if (value.IsDefault)
        {
            parameter.Value = global::System.DBNull.Value;
            return;
        }
        parameter.Value = value.Value;
    }

    public override global::TestNamespace.OrderId Parse(object? value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($"Cannot parse null as OrderId.");

        if (value is Guid g) return global::TestNamespace.OrderId.Create(g);
        if (value is string s && Guid.TryParse(s, out var parsed)) return global::TestNamespace.OrderId.Create(parsed);
        if (value is byte[] b && b.Length == 16) return global::TestNamespace.OrderId.Create(new Guid(b));

        throw new DataException($"Cannot parse {value!.GetType()} as OrderId.");
    }
}
