//HintName: TestNamespace_OrderIdJsonConverter.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class OrderIdJsonConverter : JsonConverter<global::TestNamespace.OrderId>
{
    public override global::TestNamespace.OrderId Read(ref Utf8JsonReader reader, global::System.Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null) throw new JsonException("Cannot deserialize null as OrderId.");
        return global::TestNamespace.OrderId.Create(reader.GetGuid());
    }

    public override void Write(Utf8JsonWriter writer, global::TestNamespace.OrderId value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Value);
    }
}
