//HintName: DomainPrimitivesJsonRegistration.g.cs
// <auto-generated/>
#nullable enable
using System.Text.Json;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

/// <summary>
/// Automatically registers all System.Text.Json converters for Domain Primitives.
/// Call RegisterAll(JsonSerializerOptions) once at application startup.
/// </summary>
/// <remarks>
/// AOT compatible: all converters are explicitly instantiated, no runtime reflection.
/// Thread-safe: uses double-checked locking. Safe to call multiple times.
/// </remarks>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class DomainPrimitivesJsonRegistration
{
    private static bool _registered;
    private static readonly object _lock = new object();

    /// <summary>
    /// Registers all generated JsonConverter instances into the provided JsonSerializerOptions.
    /// </summary>
    public static void RegisterAll(global::System.Text.Json.JsonSerializerOptions options)
    {
        global::System.ArgumentNullException.ThrowIfNull(options);
        if (_registered) return;
        lock (_lock)
        {
            if (_registered) return;
            options.Converters.Add(new OrderIdJsonConverter());
            _registered = true;
        }
    }
}
