//HintName: DapperDomainPrimitivesRegistration.g.cs
// <auto-generated/>
using Dapper;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

/// <summary>
/// Automatically registers all Dapper TypeHandlers for Domain Primitives.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class DapperDomainPrimitivesRegistration
{
    private static bool _registered;
    private static readonly object _lock = new object();

    /// <summary>
    /// Registers all generated TypeHandlers into Dapper's SqlMapper.
    /// Can be called safely multiple times.
    /// </summary>
    /// <remarks>
    /// <para><strong>BREAKING CHANGE (v3.0):</strong></para>
    /// <para>When Dapper encounters <c>DBNull.Value</c>, it will now throw a <c>DataException</c>
    /// instead of falling back to <c>default(T)</c>, unless the target property is nullable.
    /// Ensure your database schemas match your domain primitive nullability.</para>
    /// </remarks>
    public static void RegisterAll()
    {
        if (_registered) return;
        lock (_lock)
        {
            if (_registered) return;
            SqlMapper.AddTypeHandler(new OrderIdTypeHandler());
            _registered = true;
        }
    }
}
