//HintName: OrderIdTypeHandler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using TestNamespace;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class OrderIdTypeHandler : SqlMapper.TypeHandler<OrderId>
{
    public override void SetValue(IDbDataParameter parameter, OrderId value)
    {
        parameter.Value = value.Value;
    }

    public override OrderId Parse(object value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($"Cannot parse null as OrderId.");

        if (value is Guid g) return OrderId.Create(g);
        if (value is string s && Guid.TryParse(s, out var parsed)) return OrderId.Create(parsed);
        if (value is byte[] b && b.Length == 16) return OrderId.Create(new Guid(b));

        throw new DataException($"Cannot parse {value.GetType()} as OrderId.");
    }
}
