using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.DomainPrimitives.AspNetCore.SourceGenerators;

[Generator(LanguageNames.CSharp)]
internal sealed class ModelBinderProviderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetDomainPrimitiveInfo(ctx))
            .Where(static m => m.HasValue)
            .Select(static (m, _) => m!.Value);

        var compilationAndStructs = context.CompilationProvider.Combine(structDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndStructs,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static PrimitiveInfo? GetDomainPrimitiveInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
        if (symbol == null || !symbol.IsValueType) return null;

        var attributes = symbol.GetAttributes();


        bool isDomainPrimitive = attributes.Any(a => 
            a.AttributeClass?.ContainingNamespace.ToString() == "EricksonLopez.DomainPrimitives" &&
            (a.AttributeClass.Name.Contains("Primitive") || a.AttributeClass.Name.Contains("Id") || 
             a.AttributeClass.Name.Contains("ValueObject") || a.AttributeClass.Name.EndsWith("CodeAttribute", System.StringComparison.Ordinal) ||
             IsShortcutAttribute(a.AttributeClass.Name)));

        if (!isDomainPrimitive) return null;

        return new PrimitiveInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name);
    }

    private static readonly System.Collections.Generic.HashSet<string> Shortcuts = new()
    {
        "EmailAttribute", "PhoneAttribute", "UrlAttribute", "SlugAttribute", 
        "UsernameAttribute", "PasswordHashAttribute", "HexColorAttribute", 
        "IPAddressAttribute", "MacAddressAttribute", "IBANAttribute", 
        "ISBNAttribute", "VINAttribute", "LatitudeAttribute", "LongitudeAttribute", 
        "AgeAttribute", "WeightAttribute", "HeightAttribute", "DistanceAttribute", 
        "TemperatureAttribute", "ScoreAttribute", "QuantityAttribute", 
        "PriceAttribute", "TaxRateAttribute", "DiscountAttribute", 
        "RatingAttribute", "PercentageAttribute", "MoneyAttribute", 
        "BirthDateAttribute", "ExpirationDateAttribute", "BusinessDateAttribute", 
        "FiscalYearAttribute", "MonthAttribute", "QuarterAttribute", 
        "WeekAttribute", "DateRangeAttribute", "TimeRangeAttribute"
    };

    private static bool IsShortcutAttribute(string name) => Shortcuts.Contains(name);

    private static void Execute(Compilation compilation, ImmutableArray<PrimitiveInfo> primitives, SourceProductionContext context)
    {
        if (primitives.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using EricksonLopez.DomainPrimitives.AspNetCore;");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.DomainPrimitives.AspNetCore.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// A generated ModelBinderProvider that maps domain primitives without reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class GeneratedDomainPrimitiveModelBinderProvider : IModelBinderProvider");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Dictionary<Type, IModelBinder> _binders = new()");
        sb.AppendLine("    {");
        
        foreach (var primitive in primitives.Distinct())
        {
            string fqdn = primitive.Namespace == "<global namespace>" ? primitive.TypeName : $"{primitive.Namespace}.{primitive.TypeName}";
            sb.AppendLine($"        {{ typeof({fqdn}), new DomainPrimitiveModelBinder<{fqdn}>() }},");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public IModelBinder? GetBinder(ModelBinderProviderContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        if (_binders.TryGetValue(context.Metadata.ModelType, out var binder))");
        sb.AppendLine("        {");
        sb.AppendLine("            return binder;");
        sb.AppendLine("        }");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods to register generated domain primitive model binders.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedDomainPrimitivesServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedDomainPrimitivesModelBinding(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.Configure<MvcOptions>(options =>");
        sb.AppendLine("        {");
        sb.AppendLine("            options.ModelBinderProviders.Insert(0, new GeneratedDomainPrimitiveModelBinderProvider());");
        sb.AppendLine("        });");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedDomainPrimitiveModelBinderProvider.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal readonly struct PrimitiveInfo : System.IEquatable<PrimitiveInfo>
{
    public string Namespace { get; }
    public string TypeName { get; }

    public PrimitiveInfo(string ns, string typeName)
    {
        Namespace = ns;
        TypeName = typeName;
    }

    public bool Equals(PrimitiveInfo other) => Namespace == other.Namespace && TypeName == other.TypeName;
    public override bool Equals(object? obj) => obj is PrimitiveInfo other && Equals(other);
    public override int GetHashCode() => (Namespace.GetHashCode() * 397) ^ TypeName.GetHashCode();
}
