// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Threading.Tasks;

namespace EricksonLopez.DomainPrimitives.AspNetCore.SourceGenerators;

[Generator(LanguageNames.CSharp)]
internal sealed class ModelBinderProviderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetDomainPrimitiveInfo(ctx))
            .Where(static m => m.HasValue)
            .Select(static (m, _) => m!.Value);

        var compilationAndStructs = context.CompilationProvider.Combine(structDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndStructs,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    internal static bool IsDomainPrimitiveAttribute(AttributeData a)
    {
        var ns = a.AttributeClass?.ContainingNamespace?.ToDisplayString();
        if (ns == null || !ns.StartsWith("EricksonLopez.DomainPrimitives", StringComparison.Ordinal))
            return false;

        var name = a.AttributeClass?.Name;
        return name is not "AspNetCoreAttribute" and not "DomainPrimitivesDefaultsAttribute";
    }

    internal static PrimitiveInfo? GetDomainPrimitiveInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol || !symbol.IsValueType)
            return null;

        if (!symbol.GetAttributes().Any(IsDomainPrimitiveAttribute))
            return null;

        return new PrimitiveInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name);
    }

    internal static string GenerateSourceCode(IEnumerable<PrimitiveInfo> primitives)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using EricksonLopez.DomainPrimitives.AspNetCore;");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.DomainPrimitives.AspNetCore.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// A generated ModelBinderProvider that maps domain primitives without reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class GeneratedDomainPrimitiveModelBinderProvider : IModelBinderProvider");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Dictionary<Type, IModelBinder> _binders = new()");
        sb.AppendLine("    {");
        
        foreach (var primitive in primitives.Distinct())
        {
            string fqdn = primitive.Namespace == "<global namespace>" ? primitive.TypeName : $"{primitive.Namespace}.{primitive.TypeName}";
            sb.AppendLine($"        {{ typeof({fqdn}), new DomainPrimitiveModelBinder<{fqdn}>() }},");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public IModelBinder? GetBinder(ModelBinderProviderContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        if (_binders.TryGetValue(context.Metadata.ModelType, out var binder))");
        sb.AppendLine("        {");
        sb.AppendLine("            return binder;");
        sb.AppendLine("        }");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods to register generated domain primitive model binders.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedDomainPrimitivesServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedDomainPrimitivesModelBinding(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.Configure<MvcOptions>(options =>");
        sb.AppendLine("        {");
        sb.AppendLine("            options.ModelBinderProviders.Insert(0, new GeneratedDomainPrimitiveModelBinderProvider());");
        sb.AppendLine("        });");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void Execute(Compilation compilation, ImmutableArray<PrimitiveInfo> primitives, SourceProductionContext context)
    {
        if (primitives.IsDefaultOrEmpty) return;
        var sourceText = GenerateSourceCode(primitives);
        context.AddSource("GeneratedDomainPrimitiveModelBinderProvider.g.cs", SourceText.From(sourceText, Encoding.UTF8));
    }
}


