<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>CA1036;CA2231;CA1305;NU1603;CS0616;CA1707;CA1822;CA1861;CA1001;CA1018;CA1825;CS1591;CS1574;CA1859;CS0162</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Meziantou.Framework.StronglyTypedId" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="StronglyTypedId" />
    <PackageReference Include="ValueOf" />
    <PackageReference Include="Vogen" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives.Abstractions\EricksonLopez.DomainPrimitives.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives\EricksonLopez.DomainPrimitives.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives.Generators\EricksonLopez.DomainPrimitives.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>



