// Copyright © Erickson Lopez. MIT License.
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AwesomeAssertions;
using Dapper;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Dapper.Generated;
using Microsoft.Data.Sqlite;
using Xunit;

namespace EricksonLopez.DomainPrimitives.Dapper.Tests;

[StrongId<Guid>]
public readonly partial record struct UserId;

[StringPrimitive]
public readonly partial record struct EmailAddress;

[NumericPrimitive<int>]
public readonly partial record struct Points;

public class DapperTypeHandlerTests : IAsyncLifetime
{
    private SqliteConnection _connection = null!;

    public async Task InitializeAsync()
    {
        // 1. Register Dapper Handlers automatically generated by our Source Generator
        DapperDomainPrimitivesRegistration.RegisterAll();

        // 2. Setup SQLite In-Memory Database
        _connection = new SqliteConnection("DataSource=:memory:");
        await _connection.OpenAsync();
        
        await _connection.ExecuteAsync(@"
            CREATE TABLE Users (
                Id TEXT PRIMARY KEY,
                Email TEXT NOT NULL,
                Points INTEGER NOT NULL
            )");
    }

    public async Task DisposeAsync()
    {
        await _connection.DisposeAsync();
    }

    [Fact]
    public async Task Insert_And_Query_DomainPrimitives_Succeeds()
    {
        // Arrange
        var expectedId = UserId.Create(Guid.NewGuid());
        var expectedEmail = EmailAddress.Create("test@example.com");
        var expectedPoints = Points.Create(100);

        // Act - Insert
        await _connection.ExecuteAsync(@"
            INSERT INTO Users (Id, Email, Points)
            VALUES (@Id, @Email, @Points)", 
            new { Id = expectedId, Email = expectedEmail, Points = expectedPoints });

        // Act - Query
        var result = await _connection.QuerySingleAsync<UserEntity>(@"
            SELECT Id, Email, Points FROM Users WHERE Id = @Id", 
            new { Id = expectedId });

        // Assert
        result.Id.Should().Be(expectedId);
        result.Email.Should().Be(expectedEmail);
        result.Points.Should().Be(expectedPoints);
    }

    private sealed class UserEntity
    {
        public UserId Id { get; set; }
        public EmailAddress Email { get; set; }
        public Points Points { get; set; }
    }
}







