using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using EricksonLopez.DomainPrimitives.Generators.Models;

namespace EricksonLopez.DomainPrimitives.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class SmartEnumGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // TD-014: ForAttributeWithMetadataName for [SmartEnum<T>] — single generic trigger.
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                EricksonLopez.DomainPrimitives.Generators.Shared.GeneratorShared.SmartEnumFqn,
                predicate: static (node, ct) => EricksonLopez.DomainPrimitives.Generators.Shared.GeneratorShared.IsReadonlyRecordStruct(node, ct),
                transform: static (ctx, ct) => ExtractTypeInfo(ctx.SemanticModel, (RecordDeclarationSyntax)ctx.TargetNode, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(provider, static (spc, info) =>
        {
            var source = GenerateSmartEnum(info);
            spc.AddSource($"{info.TypeName}.g.cs", source);
        });
    }

    private static SmartEnumTypeInfo? ExtractTypeInfo(GeneratorSyntaxContext context, CancellationToken ct)
        => ExtractTypeInfo(context.SemanticModel, (RecordDeclarationSyntax)context.Node, ct);

    private static SmartEnumTypeInfo? ExtractTypeInfo(SemanticModel semanticModel, RecordDeclarationSyntax recordSyntax, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (semanticModel.GetDeclaredSymbol(recordSyntax, ct) is not INamedTypeSymbol typeSymbol)
            return null;

        AttributeData? smartEnumAttr = null;
        foreach (var attr in typeSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "SmartEnumAttribute" || attr.AttributeClass?.Name == "SmartEnum")
            {
                smartEnumAttr = attr;
                break;
            }
        }

        if (smartEnumAttr?.AttributeClass is not { TypeArguments.Length: 1 } attrType)
            return null;

        var backingType = attrType.TypeArguments[0];
        string backingFullName = backingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        bool isReferenceType = backingType.IsReferenceType;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : typeSymbol.ContainingNamespace.ToDisplayString();
        var typeName = typeSymbol.Name;

        var members = new List<string>();
        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is IFieldSymbol { IsStatic: true, IsReadOnly: true } field &&
                SymbolEqualityComparer.Default.Equals(field.Type, typeSymbol))
            {
                members.Add(field.Name);
            }
            else if (member is IPropertySymbol { IsStatic: true, IsReadOnly: true } prop &&
                     SymbolEqualityComparer.Default.Equals(prop.Type, typeSymbol))
            {
                members.Add(prop.Name);
            }
        }

        return new SmartEnumTypeInfo(ns, typeName, backingFullName, new EquatableArray<string>(members), isReferenceType);
    }

    private static string GenerateSmartEnum(SmartEnumTypeInfo info)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using EricksonLopez.DomainPrimitives;");
        sb.AppendLine("using EricksonLopez.DomainPrimitives.Validation;");
        sb.AppendLine();
        
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"[global::System.Text.Json.Serialization.JsonConverter(typeof({info.TypeName}JsonConverter))]");
        sb.AppendLine($"[global::System.ComponentModel.TypeConverter(typeof({info.TypeName}TypeConverter))]");
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"[global::System.Diagnostics.DebuggerDisplay(\"{{{info.TypeName}}}({{Name}})\")]");
        sb.AppendLine($"readonly partial record struct {info.TypeName} : ");
        sb.IncreaseIndent();
        sb.AppendLine($"EricksonLopez.DomainPrimitives.IDomainPrimitive<{info.TypeName}, {info.BackingTypeName}>,");
        sb.AppendLine($"IEquatable<{info.TypeName}>,");
        sb.AppendLine($"IParsable<{info.TypeName}>,");
        sb.AppendLine($"IFormattable,");
        sb.AppendLine($"ISpanFormattable");
        sb.DecreaseIndent();
        sb.OpenBrace();

        // Constructor and properties
        sb.AppendLine($"public {info.BackingTypeName} Value {{ get; }}");
        sb.AppendLine("public string Name { get; }");
        sb.AppendLine("public bool IsDefault => Name is null;");
        sb.AppendLine();
        sb.AppendLine($"private {info.TypeName}({info.BackingTypeName} value, string name)");
        sb.OpenBrace();
        sb.AppendLine("Value = value;");
        sb.AppendLine("Name = name;");
        sb.CloseBrace();
        sb.AppendLine();

        // PrimitiveName
        sb.AppendLine("/// <inheritdoc/>");
        sb.AppendLine($"public static string PrimitiveName => \"{info.TypeName}\";");
        sb.AppendLine();

        // Error Constants
        sb.AppendLine("/// <summary>Canonical error codes for this primitive.</summary>");
        sb.AppendLine("public static class Errors");
        sb.OpenBrace();
        sb.AppendLine("public const string NullInput = \"NULL_INPUT\";");
        sb.AppendLine("public const string Range = \"RANGE\";");
        sb.CloseBrace();
        sb.AppendLine();

        // Factory pattern compatibility
        sb.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"public static {info.TypeName} Create({info.BackingTypeName} value) => FromValue(value);");


        sb.AppendLine("/// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>");
        sb.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"public static bool TryCreate({info.BackingTypeName} value, out {info.TypeName} result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)");
        sb.OpenBrace();
        sb.AppendLine($"var success = TryFromValue(value, out result);");
        sb.AppendLine("validationError = success ? global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None : new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError(\"RANGE\", $\"Value {value} is not a valid {PrimitiveName}.\");");
        sb.AppendLine("return success;");
        sb.CloseBrace();
        sb.AppendLine();

        // Members list
        if (info.MemberNames.Length > 0)
        {
            var membersList = string.Join(", ", info.MemberNames.Values);
            sb.AppendLine($"public static readonly IReadOnlyList<{info.TypeName}> All = new {info.TypeName}[] {{ {membersList} }};");
        }
        else
        {
            sb.AppendLine($"public static readonly IReadOnlyList<{info.TypeName}> All = Array.Empty<{info.TypeName}>();");
        }
        sb.AppendLine();

        // Factory methods
        sb.AppendLine($"public static bool TryFromValue({info.BackingTypeName} value, out {info.TypeName} result)");
        sb.OpenBrace();
        sb.AppendLine($"foreach (var item in All)");
        sb.OpenBrace();
        if (info.IsReferenceType)
        {
            sb.AppendLine($"if (item.Value is not null && item.Value.Equals(value))");
        }
        else
        {
            sb.AppendLine($"if (EqualityComparer<{info.BackingTypeName}>.Default.Equals(item.Value, value))");
        }
        sb.OpenBrace();
        sb.AppendLine("result = item;");
        sb.AppendLine("return true;");
        sb.CloseBrace();
        sb.CloseBrace();
        sb.AppendLine("result = default;");
        sb.AppendLine("return false;");
        sb.CloseBrace();
        sb.AppendLine();

        sb.AppendLine($"public static {info.TypeName} FromValue({info.BackingTypeName} value)");
        sb.OpenBrace();
        sb.AppendLine($"if (TryFromValue(value, out var result)) return result;");
        sb.AppendLine($"throw new ArgumentException($\"No {info.TypeName} found with value {{value}}\", nameof(value));");
        sb.CloseBrace();
        sb.AppendLine();

        sb.AppendLine($"public static bool TryFromName(string name, out {info.TypeName} result)");
        sb.OpenBrace();
        sb.AppendLine($"foreach (var item in All)");
        sb.OpenBrace();
        sb.AppendLine($"if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))");
        sb.OpenBrace();
        sb.AppendLine("result = item;");
        sb.AppendLine("return true;");
        sb.CloseBrace();
        sb.CloseBrace();
        sb.AppendLine("result = default;");
        sb.AppendLine("return false;");
        sb.CloseBrace();
        sb.AppendLine();

        // Explicit ignoreCase overload for clarity and discoverability
        sb.AppendLine("/// <summary>Tries to get a member by name, optionally ignoring case.</summary>");
        sb.AppendLine($"public static bool TryFromName(string name, bool ignoreCase, out {info.TypeName} result)");
        sb.OpenBrace();
        sb.AppendLine("var comparison = ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;");
        sb.AppendLine($"foreach (var item in All)");
        sb.OpenBrace();
        sb.AppendLine($"if (string.Equals(item.Name, name, comparison))");
        sb.OpenBrace();
        sb.AppendLine("result = item;");
        sb.AppendLine("return true;");
        sb.CloseBrace();
        sb.CloseBrace();
        sb.AppendLine("result = default;");
        sb.AppendLine("return false;");
        sb.CloseBrace();
        sb.AppendLine();

        sb.AppendLine($"public static {info.TypeName} FromName(string name)");
        sb.OpenBrace();
        sb.AppendLine($"if (TryFromName(name, out var result)) return result;");
        sb.AppendLine($"throw new ArgumentException($\"No {info.TypeName} found with name {{name}}\", nameof(name));");
        sb.CloseBrace();
        sb.AppendLine();

        // ─── Pattern Matching ───────────────────────────────────────────────
        if (info.MemberNames.Length > 0)
        {
            // Match<TResult> — Func<TResult> variant (zero-arg lambdas)
            var matchParams = string.Join(", ", info.MemberNames.Values.Select(m => $"Func<TResult> when{m}"));
            sb.AppendLine($"/// <summary>Exhaustively matches this {info.TypeName} against all known members.</summary>");
            sb.AppendLine($"public TResult Match<TResult>({matchParams})");
            sb.OpenBrace();
            foreach (var member in info.MemberNames.Values)
            {
                sb.AppendLine($"if (Equals({member})) return when{member}();");
            }
            sb.AppendLine($"throw new InvalidOperationException($\"Unknown {info.TypeName} member: {{Name}}\");");
            sb.CloseBrace();
            sb.AppendLine();

            // Map<TResult> — Func<T, TResult> variant (passes member value to lambda)
            var mapParams = string.Join(", ", info.MemberNames.Values.Select(m => $"Func<{info.TypeName}, TResult> when{m}"));
            sb.AppendLine($"/// <summary>Exhaustively maps this {info.TypeName} to a result, passing the member as argument to each case.</summary>");
            sb.AppendLine($"public TResult Map<TResult>({mapParams})");
            sb.OpenBrace();
            foreach (var member in info.MemberNames.Values)
            {
                sb.AppendLine($"if (Equals({member})) return when{member}(this);");
            }
            sb.AppendLine($"throw new InvalidOperationException($\"Unknown {info.TypeName} member: {{Name}}\");");
            sb.CloseBrace();
            sb.AppendLine();

            // Switch — Action variant
            var switchParams = string.Join(", ", info.MemberNames.Values.Select(m => $"Action when{m}"));
            sb.AppendLine($"/// <summary>Exhaustively executes an action for each known member of {info.TypeName}.</summary>");
            sb.AppendLine($"public void Switch({switchParams})");
            sb.OpenBrace();
            foreach (var member in info.MemberNames.Values)
            {
                sb.AppendLine($"if (Equals({member})) {{ when{member}(); return; }}");
            }
            sb.AppendLine($"throw new InvalidOperationException($\"Unknown {info.TypeName} member: {{Name}}\");");
            sb.CloseBrace();
            sb.AppendLine();
        }

        // ToString and Formatting
        sb.AppendLine("public override string ToString() => Name;");
        sb.AppendLine($"public string ToString(string? format, IFormatProvider? formatProvider) => Name;");
        sb.AppendLine($"public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)");
        sb.OpenBrace();
        sb.AppendLine("var nameSpan = Name.AsSpan();");
        sb.AppendLine("if (nameSpan.Length <= destination.Length)");
        sb.OpenBrace();
        sb.AppendLine("nameSpan.CopyTo(destination);");
        sb.AppendLine("charsWritten = nameSpan.Length;");
        sb.AppendLine("return true;");
        sb.CloseBrace();
        sb.AppendLine("charsWritten = 0;");
        sb.AppendLine("return false;");
        sb.CloseBrace();
        sb.AppendLine();

        // IParsable
        sb.AppendLine($"public static {info.TypeName} Parse(string s, IFormatProvider? provider)");
        sb.OpenBrace();
        sb.AppendLine($"if (TryParse(s, provider, out var result)) return result;");
        sb.AppendLine($"throw new global::System.FormatException($\"The value '{{s}}' is not valid for {info.TypeName}.\");");
        sb.CloseBrace();
        sb.AppendLine($"public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.OpenBrace();
        sb.AppendLine("if (s is null)");
        sb.OpenBrace();
        sb.AppendLine("result = default;");
        sb.AppendLine("return false;");
        sb.CloseBrace();
        sb.AppendLine("return TryFromName(s, out result);");
        sb.CloseBrace();
        sb.AppendLine();

        // Equality members
        sb.AppendLine($"public bool Equals({info.TypeName} other)");
        sb.OpenBrace();
        if (info.IsReferenceType)
        {
            sb.AppendLine($"return Value is not null ? Value.Equals(other.Value) : other.Value is null;");
        }
        else
        {
            sb.AppendLine($"return EqualityComparer<{info.BackingTypeName}>.Default.Equals(Value, other.Value);");
        }
        sb.CloseBrace();
        sb.AppendLine();
        
        sb.AppendLine($"public override int GetHashCode()");
        sb.OpenBrace();
        if (info.IsReferenceType)
        {
            sb.AppendLine($"return Value is not null ? Value.GetHashCode() : 0;");
        }
        else
        {
            sb.AppendLine($"return EqualityComparer<{info.BackingTypeName}>.Default.GetHashCode(Value);");
        }
        sb.CloseBrace();

        EricksonLopez.DomainPrimitives.Generators.Shared.TypeConverterTemplate.GenerateTypeConverter(sb, info.TypeName, info.BackingTypeName);

        GeneratorHelpers.GenerateJsonConverter(sb, info.TypeName, info.BackingTypeName);
        
        sb.CloseBrace();
        sb.AppendLine();

        return sb.ToString();
    }
}

