<Project>
  <Import Project="../Directory.Build.props" Condition="Exists('../Directory.Build.props')" />
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591;DP0009;DP0014;DP0015;CA1305;CA1852;CA1050;CS0618;CS8618;IDE0007</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
