// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.DomainPrimitives.OpenApi.SourceGenerators;

[Generator(LanguageNames.CSharp)]
internal sealed class OpenApiSchemaFilterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetDomainPrimitiveInfo(ctx))
            .Where(static m => m.HasValue)
            .Select(static (m, _) => m!.Value);

        var compilationAndStructs = context.CompilationProvider.Combine(structDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndStructs,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    internal static bool IsDomainPrimitiveAttribute(AttributeData a)
    {
        var ns = a.AttributeClass?.ContainingNamespace?.ToDisplayString();
        if (ns == null || !ns.StartsWith("EricksonLopez.DomainPrimitives", StringComparison.Ordinal))
            return false;

        var name = a.AttributeClass?.Name;
        return name is not "OpenApiAttribute" and not "DapperAttribute" and not "EFCoreAttribute" and not "DomainPrimitivesDefaultsAttribute" and not "AspNetCoreAttribute" and not "ValueObjectAttribute";
    }

    internal static PrimitiveInfo? GetDomainPrimitiveInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
        if (symbol == null) return null;
        if (!symbol.IsValueType) return null;

        var attributes = symbol.GetAttributes();
        var primitiveAttr = attributes.FirstOrDefault(IsDomainPrimitiveAttribute);
        if (primitiveAttr == null) return null;

        var attrClass = primitiveAttr.AttributeClass!;
        var name = attrClass.Name;

        bool isSmartEnum = false;
        string openApiType = "string";
        string openApiFormat = "";

        if (name is "NumericPrimitiveAttribute" or "MoneyAttribute" or "PercentageAttribute")
        {
            openApiType = "number";
            if (name == "MoneyAttribute") openApiFormat = "double";
        }
        else if (name is "DatePrimitiveAttribute" or "BirthDateAttribute" or "ExpirationDateAttribute")
        {
            openApiType = "string";
            openApiFormat = "date";
        }
        else if (name == "StrongIdAttribute")
        {
            if (attrClass.IsGenericType && attrClass.TypeArguments[0].Name == "Guid")
            {
                openApiType = "string";
                openApiFormat = "uuid";
            }
            else if (attrClass.IsGenericType && attrClass.TypeArguments[0].Name is "Int32" or "Int64")
            {
                openApiType = "integer";
            }
        }
        else if (name == "EmailAttribute")
        {
            openApiFormat = "email";
        }
        else if (name == "UrlAttribute")
        {
            openApiFormat = "uri";
        }
        else if (name == "SmartEnumAttribute")
        {
            isSmartEnum = true;
            if (attrClass.IsGenericType)
            {
                var typeArg = attrClass.TypeArguments[0];
                if (typeArg.Name is "Int32" or "Int64")
                    openApiType = "integer";
                else
                    openApiType = "string";
            }
        }

        return new PrimitiveInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, openApiType, openApiFormat, isSmartEnum);
    }

    private static void Execute(Compilation compilation, ImmutableArray<PrimitiveInfo> primitives, SourceProductionContext context)
    {
        if (primitives.IsDefaultOrEmpty) return;

        var source = GenerateSchemaFilterSource(primitives);
        context.AddSource("DomainPrimitivesSchemaFilter.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    internal static string GenerateSchemaFilterSource(IEnumerable<PrimitiveInfo> primitives)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.OpenApi.Models;");
        sb.AppendLine("using Microsoft.OpenApi.Any;");
        sb.AppendLine("using Swashbuckle.AspNetCore.SwaggerGen;");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.DomainPrimitives.OpenApi.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Automatically maps Domain Primitives to their correct OpenAPI schema types without reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class DomainPrimitivesSchemaFilter : ISchemaFilter");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Dictionary<Type, Action<OpenApiSchema>> _schemaConfigs = new()");
        sb.AppendLine("    {");
        
        foreach (var primitive in primitives.Distinct())
        {
            string fqdn = primitive.Namespace == "<global namespace>" ? primitive.TypeName : $"{primitive.Namespace}.{primitive.TypeName}";
            
            sb.AppendLine($"        {{ typeof({fqdn}), schema => ");
            sb.AppendLine("            {");
            sb.AppendLine($"                schema.Type = \"{primitive.OpenApiType}\";");
            if (!string.IsNullOrEmpty(primitive.OpenApiFormat))
            {
                sb.AppendLine($"                schema.Format = \"{primitive.OpenApiFormat}\";");
            }
            if (primitive.IsSmartEnum)
            {
                sb.AppendLine($"                schema.Enum = new List<IOpenApiAny>();");
                sb.AppendLine($"                foreach (var item in {fqdn}.All)");
                sb.AppendLine($"                {{");
                if (primitive.OpenApiType == "integer")
                {
                    sb.AppendLine($"                    schema.Enum.Add(new OpenApiInteger((int)Convert.ChangeType(item.Value, typeof(int))));");
                }
                else
                {
                    sb.AppendLine($"                    schema.Enum.Add(new OpenApiString(item.Name));");
                }
                sb.AppendLine($"                }}");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        },");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public void Apply(OpenApiSchema schema, SchemaFilterContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_schemaConfigs.TryGetValue(context.Type, out var configAction))");
        sb.AppendLine("        {");
        sb.AppendLine("            configAction(schema);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}


