// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using AwesomeAssertions;
using Xunit;

namespace EricksonLopez.DomainPrimitives.Dapper.SourceGenerators.Tests;

public class DapperGeneratorsUnitTests
{
    private static string Normalize(string code) =>
        string.Join("\n", code.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None)
            .Select(l => l.TrimEnd()));

    [Fact]
    public void GenerateTypeHandler_StringPrimitive_ProducesExactCode()
    {
        var info = new PrimitiveInfo("MyCompany.Domain", "CustomerId", "string", isSmartEnum: false);
        var code = DapperTypeHandlerGenerator.GenerateTypeHandler(info);

        var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using MyCompany.Domain;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class CustomerIdTypeHandler : SqlMapper.TypeHandler<CustomerId>
{
    public override void SetValue(IDbDataParameter parameter, CustomerId value)
    {
        parameter.Value = value.Value;
    }

    public override CustomerId Parse(object value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($""Cannot parse null as CustomerId."");

        if (value is string s) return CustomerId.Create(s);
        return CustomerId.Create(value.ToString() ?? string.Empty);

        throw new DataException($""Cannot parse {value.GetType()} as CustomerId."");
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateTypeHandler_GlobalNamespace_OmitsUsingNamespace()
    {
        var info = new PrimitiveInfo("<global namespace>", "GlobalId", "string", isSmartEnum: false);
        var code = DapperTypeHandlerGenerator.GenerateTypeHandler(info);

        code.Should().NotContain("using <global namespace>;");
        code.Should().Contain("internal sealed class GlobalIdTypeHandler : SqlMapper.TypeHandler<GlobalId>");
    }

    [Fact]
    public void GenerateTypeHandler_GuidBacked_ProducesExactGuidParsers()
    {
        var info = new PrimitiveInfo("MyCompany.Domain", "OrderId", "global::Guid", isSmartEnum: false);
        var code = DapperTypeHandlerGenerator.GenerateTypeHandler(info);
        var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using MyCompany.Domain;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class OrderIdTypeHandler : SqlMapper.TypeHandler<OrderId>
{
    public override void SetValue(IDbDataParameter parameter, OrderId value)
    {
        parameter.Value = value.Value;
    }

    public override OrderId Parse(object value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($""Cannot parse null as OrderId."");

        if (value is Guid g) return OrderId.Create(g);
        if (value is string s && Guid.TryParse(s, out var parsed)) return OrderId.Create(parsed);
        if (value is byte[] b && b.Length == 16) return OrderId.Create(new Guid(b));

        throw new DataException($""Cannot parse {value.GetType()} as OrderId."");
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateTypeHandler_DateOnlyBacked_ProducesExactDateOnlyParsers()
    {
        var info = new PrimitiveInfo("MyCompany.Domain", "BirthDate", "global::System.DateOnly", isSmartEnum: false);
        var code = DapperTypeHandlerGenerator.GenerateTypeHandler(info);
var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using MyCompany.Domain;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class BirthDateTypeHandler : SqlMapper.TypeHandler<BirthDate>
{
    public override void SetValue(IDbDataParameter parameter, BirthDate value)
    {
        parameter.Value = value.Value;
    }

    public override BirthDate Parse(object value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($""Cannot parse null as BirthDate."");

        if (value is DateTime dt) return BirthDate.Create(DateOnly.FromDateTime(dt));
        if (value is string s && DateOnly.TryParse(s, out var parsed)) return BirthDate.Create(parsed);

        throw new DataException($""Cannot parse {value.GetType()} as BirthDate."");
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateTypeHandler_NumericPrimitive_ProducesExactConvertChangeType()
    {
        var info = new PrimitiveInfo("MyCompany.Domain", "Quantity", "int", isSmartEnum: false);
        var code = DapperTypeHandlerGenerator.GenerateTypeHandler(info);
var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using MyCompany.Domain;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class QuantityTypeHandler : SqlMapper.TypeHandler<Quantity>
{
    public override void SetValue(IDbDataParameter parameter, Quantity value)
    {
        parameter.Value = value.Value;
    }

    public override Quantity Parse(object value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($""Cannot parse null as Quantity."");

        try
        {
            var converted = (int)Convert.ChangeType(value, typeof(int));
            return Quantity.Create(converted);
        }
        catch (InvalidCastException)
        {
        }

        throw new DataException($""Cannot parse {value.GetType()} as Quantity."");
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateTypeHandler_SmartEnum_ProducesExactFromValueFactory()
    {
        var info = new PrimitiveInfo("MyCompany.Domain", "OrderStatus", "int", isSmartEnum: true);
        var code = DapperTypeHandlerGenerator.GenerateTypeHandler(info);
var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using MyCompany.Domain;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class OrderStatusTypeHandler : SqlMapper.TypeHandler<OrderStatus>
{
    public override void SetValue(IDbDataParameter parameter, OrderStatus value)
    {
        parameter.Value = value.Value;
    }

    public override OrderStatus Parse(object value)
    {
        if (value is null || value == DBNull.Value)
            throw new DataException($""Cannot parse null as OrderStatus."");

        try
        {
            var converted = (int)Convert.ChangeType(value, typeof(int));
            return OrderStatus.FromValue(converted);
        }
        catch (InvalidCastException)
        {
        }

        throw new DataException($""Cannot parse {value.GetType()} as OrderStatus."");
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateRegistration_WithMultipleHandlers_ProducesExactCode()
    {
        var handlers = new List<string> { "CustomerIdTypeHandler", "OrderIdTypeHandler" };
        var code = DapperTypeHandlerGenerator.GenerateRegistration(handlers);

        var expected = @"// <auto-generated/>
using Dapper;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

/// <summary>
/// Automatically registers all Dapper TypeHandlers for Domain Primitives.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class DapperDomainPrimitivesRegistration
{
    private static bool _registered;
    private static readonly object _lock = new object();

    /// <summary>
    /// Registers all generated TypeHandlers into Dapper's SqlMapper.
    /// Can be called safely multiple times.
    /// </summary>
    /// <remarks>
    /// <para><strong>BREAKING CHANGE (v3.0):</strong></para>
    /// <para>When Dapper encounters <c>DBNull.Value</c>, it will now throw a <c>DataException</c>
    /// instead of falling back to <c>default(T)</c>, unless the target property is nullable.
    /// Ensure your database schemas match your domain primitive nullability.</para>
    /// </remarks>
    public static void RegisterAll()
    {
        if (_registered) return;
        lock (_lock)
        {
            if (_registered) return;
            SqlMapper.AddTypeHandler(new CustomerIdTypeHandler());
            SqlMapper.AddTypeHandler(new OrderIdTypeHandler());
            _registered = true;
        }
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateRegistration_EmptyHandlers_ProducesEmptyRegistrationBlock()
    {
        var handlers = new List<string>();
        var code = DapperTypeHandlerGenerator.GenerateRegistration(handlers);

        code.Should().Contain("public static class DapperDomainPrimitivesRegistration");
        code.Should().NotContain("SqlMapper.AddTypeHandler");
    }

    [Fact]
    public void GenerateValueObjectDapperExtensions_MultiProperty_ProducesExactCode()
    {
        var props = new EquatableArray<ValueObjectProperty>(ImmutableArray.Create(
            new ValueObjectProperty("Amount", "decimal"),
            new ValueObjectProperty("Currency", "string")));

        var info = new ValueObjectInfo("MyCompany.Domain", "Money", props);
        var code = DapperValueObjectGenerator.GenerateValueObjectDapperExtensions(info);
var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;
using MyCompany.Domain;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

/// <summary>
/// Dapper extensions for the Money Value Object.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class MoneyDapperExtensions
{
    /// <summary>
    /// Adds the properties of the Money to the DynamicParameters.
    /// </summary>
    public static void AddParameters(this DynamicParameters parameters, Money value, string prefix = """")
    {
        parameters.Add($""{prefix}Amount"", value.Amount);
        parameters.Add($""{prefix}Currency"", value.Currency);
    }

    /// <summary>
    /// Parses a Money from an IDataRecord.
    /// </summary>
    public static Money ParseValueObject(this IDataRecord record, string prefix = """")
    {
        var idx_Amount = record.GetOrdinal($""{prefix}Amount"");
        var val_Amount = record.IsDBNull(idx_Amount) ? default : (decimal)record.GetValue(idx_Amount);
        var idx_Currency = record.GetOrdinal($""{prefix}Currency"");
        var val_Currency = record.IsDBNull(idx_Currency) ? default : (string)record.GetValue(idx_Currency);
        return Money.Create(val_Amount!, val_Currency!);
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void GenerateValueObjectDapperExtensions_EmptyProperties_ProducesExactCode()
    {
        var props = new EquatableArray<ValueObjectProperty>(ImmutableArray<ValueObjectProperty>.Empty);
        var info = new ValueObjectInfo("<global namespace>", "EmptyVo", props);
        var code = DapperValueObjectGenerator.GenerateValueObjectDapperExtensions(info);
        var expected = @"// <auto-generated/>
#nullable enable
using System;
using System.Data;
using Dapper;

namespace EricksonLopez.DomainPrimitives.Dapper.Generated;

/// <summary>
/// Dapper extensions for the EmptyVo Value Object.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class EmptyVoDapperExtensions
{
    /// <summary>
    /// Adds the properties of the EmptyVo to the DynamicParameters.
    /// </summary>
    public static void AddParameters(this DynamicParameters parameters, EmptyVo value, string prefix = """")
    {
    }

    /// <summary>
    /// Parses a EmptyVo from an IDataRecord.
    /// </summary>
    public static EmptyVo ParseValueObject(this IDataRecord record, string prefix = """")
    {
        return EmptyVo.Create();
    }
}
";
        Normalize(code).Should().Be(Normalize(expected));
    }

    [Fact]
    public void ValueObjectInfo_EqualityAndHashCode_Comprehensive()
    {
        var props1 = new EquatableArray<ValueObjectProperty>(ImmutableArray.Create(new ValueObjectProperty("X", "int")));
        var props2 = new EquatableArray<ValueObjectProperty>(ImmutableArray.Create(new ValueObjectProperty("X", "int")));
        var props3 = new EquatableArray<ValueObjectProperty>(ImmutableArray.Create(new ValueObjectProperty("Y", "int")));

        var info1 = new ValueObjectInfo("NS", "Vo", props1);
        var info2 = new ValueObjectInfo("NS", "Vo", props2);
        var info3 = new ValueObjectInfo("OtherNS", "Vo", props1);
        var info4 = new ValueObjectInfo("NS", "OtherVo", props1);
        var info5 = new ValueObjectInfo("NS", "Vo", props3);

        Assert.True(info1.Equals(info1));
        Assert.True(info1.Equals(info2));
        Assert.True(info1.Equals((object)info2));
        Assert.False(info1.Equals(info3));
        Assert.False(info1.Equals(info4));
        Assert.False(info1.Equals(info5));
        Assert.False(info1.Equals((object?)null));
        Assert.False(info1.Equals((ValueObjectInfo?)null));
        Assert.False(info1.Equals((object)"some string"));

        info1.GetHashCode().Should().Be(info2.GetHashCode());
        info1.GetHashCode().Should().NotBe(info3.GetHashCode());
        info1.GetHashCode().Should().NotBe(info4.GetHashCode());
        info1.GetHashCode().Should().NotBe(info5.GetHashCode());
    }

    [Fact]
    public void ValueObjectProperty_EqualityAndHashCode_Comprehensive()
    {
        var p1 = new ValueObjectProperty("Name", "string");
        var p2 = new ValueObjectProperty("Name", "string");
        var p3 = new ValueObjectProperty("OtherName", "string");
        var p4 = new ValueObjectProperty("Name", "int");

        Assert.True(p1.Equals(p2));
        Assert.True(p1.Equals((object)p2));
        Assert.False(p1.Equals(p3));
        Assert.False(p1.Equals(p4));
        Assert.False(p1.Equals((object?)null));
        Assert.False(p1.Equals((object)"string"));

        p1.GetHashCode().Should().Be(p2.GetHashCode());
        p1.GetHashCode().Should().NotBe(p3.GetHashCode());
    }

    [Fact]
    public void EquatableArray_EqualityAndHashCode_Comprehensive()
    {
        var arr1 = new EquatableArray<int>(ImmutableArray.Create(1, 2, 3));
        var arr2 = new EquatableArray<int>(new[] { 1, 2, 3 });
        var arr3 = new EquatableArray<int>(ImmutableArray.Create(1, 2, 4));
        var arr4 = new EquatableArray<int>(ImmutableArray.Create(1, 2));
        var defaultArr = default(EquatableArray<int>);

        arr1.Length.Should().Be(3);
        arr1[1].Should().Be(2);
        Assert.True(arr1.Equals(arr2));
        Assert.True(arr1.Equals((object)arr2));
        Assert.False(arr1.Equals(arr3));
        Assert.False(arr1.Equals(arr4));
        Assert.False(arr1.Equals(defaultArr));
        Assert.False(arr1.Equals((object?)null));
        Assert.False(arr1.Equals((object)"not an array"));

        arr1.GetHashCode().Should().Be(arr2.GetHashCode());
        arr1.GetHashCode().Should().NotBe(arr3.GetHashCode());

        defaultArr.Length.Should().Be(0);
        defaultArr.Values.Should().BeEmpty();
    }

    [Fact]
    public void PrimitiveInfo_EqualityAndHashCode_Comprehensive()
    {
        var info1 = new PrimitiveInfo("NS", "T1", "string", isSmartEnum: false);
        var info2 = new PrimitiveInfo("NS", "T1", "string", isSmartEnum: false);
        var diffNs = new PrimitiveInfo("OtherNS", "T1", "string", isSmartEnum: false);
        var diffName = new PrimitiveInfo("NS", "T2", "string", isSmartEnum: false);
        var diffBacking = new PrimitiveInfo("NS", "T1", "int", isSmartEnum: false);
        var diffEnum = new PrimitiveInfo("NS", "T1", "string", isSmartEnum: true);

        Assert.True(info1.Equals(info2));
        Assert.True(info1.Equals((object)info2));
        Assert.False(info1.Equals(diffNs));
        Assert.False(info1.Equals(diffName));
        Assert.False(info1.Equals(diffBacking));
        Assert.False(info1.Equals(diffEnum));
        Assert.False(info1.Equals((object?)null));
        Assert.False(info1.Equals("not an info"));

        info1.GetHashCode().Should().Be(info2.GetHashCode());
        info1.GetHashCode().Should().NotBe(diffNs.GetHashCode());
        info1.GetHashCode().Should().NotBe(diffName.GetHashCode());
        info1.GetHashCode().Should().NotBe(diffBacking.GetHashCode());
        info1.GetHashCode().Should().NotBe(diffEnum.GetHashCode());
    }
}




