<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives.Dapper.SourceGenerators\EricksonLopez.DomainPrimitives.Dapper.SourceGenerators.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives.Abstractions\EricksonLopez.DomainPrimitives.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.DomainPrimitives\EricksonLopez.DomainPrimitives.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies.Net80" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="Verify.Xunit" />
  </ItemGroup>
</Project>
