#pragma warning disable CS1591
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.DomainPrimitives.Dapper.SourceGenerators;

[Generator(LanguageNames.CSharp)]
internal sealed class DapperValueObjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is RecordDeclarationSyntax rds && rds.ClassOrStructKeyword.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StructKeyword),
                transform: static (ctx, _) => GetValueObjectInfo(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(structDeclarations, static (spc, info) => Execute(info, spc));
    }

    private static ValueObjectInfo? GetValueObjectInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (RecordDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        bool hasValueObject = false;
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "ValueObjectAttribute" &&
                attr.AttributeClass.ContainingNamespace.ToString() == "EricksonLopez.DomainPrimitives")
            {
                hasValueObject = true;
            }
        }

        if (!hasValueObject) return null;

        var properties = new List<ValueObjectProperty>();

        foreach (var member in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.IsStatic) continue;
            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            string typeName = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            properties.Add(new ValueObjectProperty(member.Name, typeName));
        }

        return new ValueObjectInfo(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            new EquatableArray<ValueObjectProperty>(properties.ToImmutableArray())
        );
    }

    private static void Execute(ValueObjectInfo info, SourceProductionContext context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Dapper;");
        if (info.Namespace != "<global namespace>")
        {
            sb.AppendLine($"using {info.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.DomainPrimitives.Dapper.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Dapper extensions for the {info.TypeName} Value Object.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public static class {info.TypeName}DapperExtensions");
        sb.AppendLine("{");
        
        // AddParameters
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Adds the properties of the {info.TypeName} to the DynamicParameters.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static void AddParameters(this DynamicParameters parameters, {info.TypeName} value, string prefix = \"\")");
        sb.AppendLine("    {");
        if (info.Properties.Length > 0)
        {
            foreach (var prop in info.Properties.Values)
            {
                sb.AppendLine($"        parameters.Add($\"{{prefix}}{prop.Name}\", value.{prop.Name});");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Parse (IDataRecord)
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Parses a {info.TypeName} from an IDataRecord.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static {info.TypeName} ParseValueObject(this IDataRecord record, string prefix = \"\")");
        sb.AppendLine("    {");
        
        if (info.Properties.Length > 0)
        {
            foreach (var prop in info.Properties.Values)
            {
                sb.AppendLine($"        var idx_{prop.Name} = record.GetOrdinal($\"{{prefix}}{prop.Name}\");");
                sb.AppendLine($"        var val_{prop.Name} = record.IsDBNull(idx_{prop.Name}) ? default : ({prop.Type})record.GetValue(idx_{prop.Name});");
            }

            var args = string.Join(", ", info.Properties.Values.Select(p => $"val_{p.Name}!"));
            sb.AppendLine($"        return {info.TypeName}.Create({args});");
        }
        else
        {
            sb.AppendLine($"        return {info.TypeName}.Create();");
        }
        
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource($"{info.TypeName}DapperExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal sealed class ValueObjectInfo : IEquatable<ValueObjectInfo>
{
    public string Namespace { get; }
    public string TypeName { get; }
    public EquatableArray<ValueObjectProperty> Properties { get; }

    public ValueObjectInfo(string ns, string typeName, EquatableArray<ValueObjectProperty> properties)
    {
        Namespace = ns;
        TypeName = typeName;
        Properties = properties;
    }

    public bool Equals(ValueObjectInfo? other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;
        return Namespace == other.Namespace && TypeName == other.TypeName && Properties.Equals(other.Properties);
    }

    public override bool Equals(object? obj) => Equals(obj as ValueObjectInfo);
    public override int GetHashCode()
    {
        unchecked
        {
            var hashCode = Namespace.GetHashCode();
            hashCode = (hashCode * 397) ^ TypeName.GetHashCode();
            hashCode = (hashCode * 397) ^ Properties.GetHashCode();
            return hashCode;
        }
    }
}

[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal readonly struct ValueObjectProperty : IEquatable<ValueObjectProperty>
{
    public string Name { get; }
    public string Type { get; }

    public ValueObjectProperty(string name, string type)
    {
        Name = name;
        Type = type;
    }

    public bool Equals(ValueObjectProperty other) => Name == other.Name && Type == other.Type;
    public override bool Equals(object? obj) => obj is ValueObjectProperty other && Equals(other);
    public override int GetHashCode()
    {
        unchecked
        {
            return (Name.GetHashCode() * 397) ^ Type.GetHashCode();
        }
    }
}

[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>
    where T : IEquatable<T>
{
    private readonly ImmutableArray<T> _array;

    public EquatableArray(ImmutableArray<T> array) => _array = array;
    public EquatableArray(IEnumerable<T> items) => _array = items.ToImmutableArray();

    public ImmutableArray<T> Values => _array.IsDefault ? ImmutableArray<T>.Empty : _array;
    public int Length => Values.Length;
    public T this[int index] => Values[index];

    public bool Equals(EquatableArray<T> other)
    {
        var self = Values;
        var otherValues = other.Values;

        if (self.Length != otherValues.Length)
            return false;

        for (int i = 0; i < self.Length; i++)
        {
            if (!self[i].Equals(otherValues[i]))
                return false;
        }

        return true;
    }

    public override bool Equals(object? obj) => obj is EquatableArray<T> other && Equals(other);

    public override int GetHashCode()
    {
        var values = Values;
        unchecked
        {
            int hash = 17;
            foreach (var item in values)
                hash = hash * 31 + item.GetHashCode();
            return hash;
        }
    }

    public static implicit operator EquatableArray<T>(ImmutableArray<T> array) => new(array);
}
