// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.DomainPrimitives.Dapper.SourceGenerators;

[Generator(LanguageNames.CSharp)]
internal sealed class DapperValueObjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is RecordDeclarationSyntax rds && rds.ClassOrStructKeyword.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StructKeyword),
                transform: static (ctx, _) => GetValueObjectInfo(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(structDeclarations, static (spc, info) => Execute(info, spc));
    }

    private static ValueObjectInfo? GetValueObjectInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (RecordDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        bool hasValueObject = symbol.GetAttributes().Any(attr =>
            attr.AttributeClass?.Name == "ValueObjectAttribute" &&
            attr.AttributeClass.ContainingNamespace.ToString() == "EricksonLopez.DomainPrimitives");

        if (!hasValueObject) return null;

        var properties = new List<ValueObjectProperty>();

        foreach (var member in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.IsStatic) continue;
            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            string typeName = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            properties.Add(new ValueObjectProperty(member.Name, typeName));
        }

        return new ValueObjectInfo(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            new EquatableArray<ValueObjectProperty>(properties.ToImmutableArray())
        );
    }

    private static void Execute(ValueObjectInfo info, SourceProductionContext context)
    {
        var code = GenerateValueObjectDapperExtensions(info);
        context.AddSource($"{info.TypeName}DapperExtensions.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    internal static string GenerateValueObjectDapperExtensions(ValueObjectInfo info)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Dapper;");
        if (info.Namespace != "<global namespace>")
        {
            sb.AppendLine($"using {info.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.DomainPrimitives.Dapper.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Dapper extensions for the {info.TypeName} Value Object.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public static class {info.TypeName}DapperExtensions");
        sb.AppendLine("{");
        
        // AddParameters
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Adds the properties of the {info.TypeName} to the DynamicParameters.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static void AddParameters(this DynamicParameters parameters, {info.TypeName} value, string prefix = \"\")");
        sb.AppendLine("    {");
        foreach (var prop in info.Properties.Values)
        {
            sb.AppendLine($"        parameters.Add($\"{{prefix}}{prop.Name}\", value.{prop.Name});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Parse (IDataRecord)
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Parses a {info.TypeName} from an IDataRecord.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static {info.TypeName} ParseValueObject(this IDataRecord record, string prefix = \"\")");
        sb.AppendLine("    {");
        
        if (info.Properties.Length == 0)
        {
            sb.AppendLine($"        return {info.TypeName}.Create();");
        }
        else
        {
            foreach (var prop in info.Properties.Values)
            {
                sb.AppendLine($"        var idx_{prop.Name} = record.GetOrdinal($\"{{prefix}}{prop.Name}\");");
                sb.AppendLine($"        var val_{prop.Name} = record.IsDBNull(idx_{prop.Name}) ? default : ({prop.Type})record.GetValue(idx_{prop.Name});");
            }

            var args = string.Join(", ", info.Properties.Values.Select(p => $"val_{p.Name}!"));
            sb.AppendLine($"        return {info.TypeName}.Create({args});");
        }
        
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
