<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>
</Project>
