//HintName: ReportingMonth.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(ReportingMonthJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(ReportingMonthTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{ReportingMonth}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial record struct ReportingMonth :
    IDomainPrimitive<ReportingMonth, System.DateOnly>,
    IParsable<ReportingMonth>,
    ISpanParsable<ReportingMonth>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<ReportingMonth>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<ReportingMonth>,
    IComparable,
    System.Numerics.IEqualityOperators<ReportingMonth, ReportingMonth, bool>,
    System.Numerics.IComparisonOperators<ReportingMonth, ReportingMonth, bool>
{
    private readonly System.DateOnly _value;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => _value.Equals(default(System.DateOnly));

    /// <summary>The underlying primitive value.</summary>
    public System.DateOnly Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of ReportingMonth. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "ReportingMonth";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Temporal = "TEMPORAL";
        public const string Invariant = "INVARIANT";
    }

    private ReportingMonth(System.DateOnly value) => _value = value;

    // ─── Validation ─────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Validate(System.DateOnly value)
    {
        var error = TryValidate(value);
        if (error.IsError)
        {
            throw new DomainPrimitiveValidationException(error);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(System.DateOnly value)
    {
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // ─── Factory Methods ─────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ReportingMonth Create(System.DateOnly value)
    {
        Validate(value);
        return new ReportingMonth(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(System.DateOnly value, out ReportingMonth result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new ReportingMonth(value);
        return true;
    }

    // ─── Parsing ─────────────────────────────────────────────────────

    public static ReportingMonth Parse(string s) => Parse(s, null);
    public static ReportingMonth Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for ReportingMonth.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out ReportingMonth result)
    {
        if (System.DateOnly.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static ReportingMonth Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out ReportingMonth result)
    {
        if (System.DateOnly.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static ReportingMonth Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out ReportingMonth result)
    {
        int count = System.Text.Encoding.UTF8.GetCharCount(utf8Text);
        if (count <= 512)
        {
            System.Span<char> chars = stackalloc char[count];
            System.Text.Encoding.UTF8.GetChars(utf8Text, chars);
            if (System.DateOnly.TryParse((System.ReadOnlySpan<char>)chars, provider, out var parsed))
            {
                if (TryCreate(parsed, out result, out _)) return true;
            }
        }
        else
        {
            var rented = System.Buffers.ArrayPool<char>.Shared.Rent(count);
            try
            {
                System.Text.Encoding.UTF8.GetChars(utf8Text, rented);
                if (System.DateOnly.TryParse((System.ReadOnlySpan<char>)rented.AsSpan(0, count), provider, out var parsed))
                {
                    if (TryCreate(parsed, out result, out _)) return true;
                }
            }
            finally
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented);
            }
        }
        result = default;
        return false;
    }
    #endif

    // ─── Formatting ──────────────────────────────────────────────────

    public void Deconstruct(out System.DateOnly value) => value = _value;

    public override string ToString() => _value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
            var s = _value.ToString(format != default ? format.ToString() : null, provider);
            return System.Text.Encoding.UTF8.TryGetBytes(s.AsSpan(), utf8Destination, out bytesWritten);
    }
    #endif

    // ─── Operators ────────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator System.DateOnly(ReportingMonth value) => value._value;

    public static explicit operator ReportingMonth(System.DateOnly value) => Create(value);

    // ─── Comparison ──────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(ReportingMonth other) => _value.CompareTo(other._value);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        ReportingMonth other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type ReportingMonth.")
    };

    public static bool operator <(ReportingMonth left, ReportingMonth right) => left.CompareTo(right) < 0;
    public static bool operator <=(ReportingMonth left, ReportingMonth right) => left.CompareTo(right) <= 0;
    public static bool operator >(ReportingMonth left, ReportingMonth right) => left.CompareTo(right) > 0;
    public static bool operator >=(ReportingMonth left, ReportingMonth right) => left.CompareTo(right) >= 0;

    // ─── TypeConverter ───────────────────────────────────────────────

    public sealed class ReportingMonthTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType) => sourceType == typeof(string) || sourceType == typeof(System.DateOnly) || base.CanConvertFrom(context, sourceType);
        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return Parse(s, culture);
            if (value is System.DateOnly v) return Create(v);
            return base.ConvertFrom(context, culture, value);
        }
        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType) => destinationType == typeof(string) || destinationType == typeof(System.DateOnly) || base.CanConvertTo(context, destinationType);
        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is ReportingMonth instance)
            {
                if (destinationType == typeof(string)) return instance.ToString();
                if (destinationType == typeof(System.DateOnly)) return instance.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class ReportingMonthJsonConverter : global::System.Text.Json.Serialization.JsonConverter<ReportingMonth>
    {
        public override ReportingMonth Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            var value = global::System.Text.Json.JsonSerializer.Deserialize<System.DateOnly>(ref reader, options);
            if (ReportingMonth.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid ReportingMonth: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ReportingMonth value, global::System.Text.Json.JsonSerializerOptions options)
        {
            global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
        }
    }

}
