//HintName: ReportingQuarter.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(ReportingQuarterJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(ReportingQuarterTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{ReportingQuarter}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Diagnostics.DebuggerStepThrough]
public readonly partial record struct ReportingQuarter :
    IDomainPrimitive<ReportingQuarter, System.DateOnly>,
    IParsable<ReportingQuarter>,
    ISpanParsable<ReportingQuarter>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<ReportingQuarter>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<ReportingQuarter>,
    IComparable,
    System.Numerics.IEqualityOperators<ReportingQuarter, ReportingQuarter, bool>,
    System.Numerics.IComparisonOperators<ReportingQuarter, ReportingQuarter, bool>
{
    private readonly System.DateOnly _value;
    private readonly bool _isInitialized;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => !_isInitialized;

    /// <summary>The underlying primitive value.</summary>
    public System.DateOnly Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of ReportingQuarter. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "ReportingQuarter";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Temporal = "TEMPORAL";
        public const string Invariant = "INVARIANT";
    }

    private ReportingQuarter(System.DateOnly value)
    {
        _value = value;
        _isInitialized = true;
    }

    // ─── Validation ─────────────────────────────────────────────────

    #if NET8_0_OR_GREATER
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Validate(System.DateOnly value) => Validate(value, null);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Validate(System.DateOnly value, global::System.TimeProvider? timeProvider)
    {
        var error = TryValidate(value, timeProvider);
        if (error.IsError) throw new DomainPrimitiveValidationException(error);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(System.DateOnly value, global::System.TimeProvider? timeProvider = null)
    {
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }
    #else
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Validate(System.DateOnly value)
    {
        var error = TryValidate(value);
        if (error.IsError) throw new DomainPrimitiveValidationException(error);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(System.DateOnly value)
    {
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }
    #endif

    // ─── Factory Methods ─────────────────────────────────────────────

    #if NET8_0_OR_GREATER
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ReportingQuarter Create(System.DateOnly value) => Create(value, null);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ReportingQuarter Create(System.DateOnly value, global::System.TimeProvider? timeProvider)
    {
        Validate(value, timeProvider);
        return new ReportingQuarter(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(System.DateOnly value, out ReportingQuarter result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError) => TryCreate(value, null, out result, out validationError);

    /// <summary>Tries to create a valid instance using a custom TimeProvider. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(System.DateOnly value, global::System.TimeProvider? timeProvider, out ReportingQuarter result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value, timeProvider);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new ReportingQuarter(value);
        return true;
    }

    #else
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ReportingQuarter Create(System.DateOnly value)
    {
        Validate(value);
        return new ReportingQuarter(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(System.DateOnly value, out ReportingQuarter result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new ReportingQuarter(value);
        return true;
    }

    #endif
    // ─── Parsing ─────────────────────────────────────────────────────

    public static ReportingQuarter Parse(string s) => Parse(s, null);
    public static ReportingQuarter Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for ReportingQuarter.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out ReportingQuarter result)
    {
        if (System.DateOnly.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static ReportingQuarter Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out ReportingQuarter result)
    {
        if (System.DateOnly.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static ReportingQuarter Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out ReportingQuarter result)
    {
        if (utf8Text.Length > 128)
        {
            result = default;
            return false;
        }
        int count = System.Text.Encoding.UTF8.GetCharCount(utf8Text);
        if (count <= 128)
        {
            System.Span<char> chars = stackalloc char[count];
            System.Text.Encoding.UTF8.GetChars(utf8Text, chars);
            if (System.DateOnly.TryParse((System.ReadOnlySpan<char>)chars, provider, out var parsed))
            {
                if (TryCreate(parsed, out result, out _)) return true;
            }
        }
        else
        {
            var rented = System.Buffers.ArrayPool<char>.Shared.Rent(count);
            try
            {
                System.Text.Encoding.UTF8.GetChars(utf8Text, rented);
                if (System.DateOnly.TryParse((System.ReadOnlySpan<char>)rented.AsSpan(0, count), provider, out var parsed))
                {
                    if (TryCreate(parsed, out result, out _)) return true;
                }
            }
            finally
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented, clearArray: true);
            }
        }
        result = default;
        return false;
    }
    #endif

    // ─── Formatting ──────────────────────────────────────────────────

    public void Deconstruct(out System.DateOnly value) => value = _value;

    public override string ToString() => IsDefault ? string.Empty : _value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider)
        => IsDefault ? string.Empty : _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
            var s = _value.ToString(format != default ? format.ToString() : null, provider);
            return System.Text.Encoding.UTF8.TryGetBytes(s.AsSpan(), utf8Destination, out bytesWritten);
    }
    #endif

    // ─── Operators ────────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator System.DateOnly(ReportingQuarter value) =>
        value.IsDefault ? throw new InvalidOperationException("Cannot convert a default ReportingQuarter to System.DateOnly. Check IsDefault before casting.") : value._value;

    public static explicit operator ReportingQuarter(System.DateOnly value) => Create(value);

    // ─── Comparison ──────────────────────────────────────────────────

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(ReportingQuarter other)
    {
        if (IsDefault && other.IsDefault) return 0;
        if (IsDefault) return -1;
        if (other.IsDefault) return 1;
        return _value.CompareTo(other._value);
    }

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        ReportingQuarter other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type ReportingQuarter.")
    };

    public static bool operator <(ReportingQuarter left, ReportingQuarter right) => left.CompareTo(right) < 0;
    public static bool operator <=(ReportingQuarter left, ReportingQuarter right) => left.CompareTo(right) <= 0;
    public static bool operator >(ReportingQuarter left, ReportingQuarter right) => left.CompareTo(right) > 0;
    public static bool operator >=(ReportingQuarter left, ReportingQuarter right) => left.CompareTo(right) >= 0;

    // ─── TypeConverter ───────────────────────────────────────────────

    public sealed class ReportingQuarterTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType) => sourceType == typeof(string) || sourceType == typeof(System.DateOnly) || base.CanConvertFrom(context, sourceType);
        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return Parse(s, culture);
            if (value is System.DateOnly v) return Create(v);
            return base.ConvertFrom(context, culture, value);
        }
        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType) => destinationType == typeof(string) || destinationType == typeof(System.DateOnly) || base.CanConvertTo(context, destinationType);
        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is ReportingQuarter instance)
            {
                if (destinationType == typeof(string)) return instance.ToString();
                if (destinationType == typeof(System.DateOnly)) return instance.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class ReportingQuarterJsonConverter : global::System.Text.Json.Serialization.JsonConverter<ReportingQuarter>
    {
        public override ReportingQuarter Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) throw new global::System.Text.Json.JsonException($"Cannot deserialize null into non-nullable domain primitive 'ReportingQuarter'.");

            #if NET8_0_OR_GREATER
            var stringValue = reader.GetString();
            if (stringValue is null || !global::System.DateOnly.TryParse(stringValue, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var value)) throw new global::System.Text.Json.JsonException($"Invalid ReportingQuarter: expected valid DateOnly ISO-8601 string.");
            if (ReportingQuarter.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid ReportingQuarter: {err.Message}");
            #else
            var value = global::System.Text.Json.JsonSerializer.Deserialize<System.DateOnly>(ref reader, options);
            if (ReportingQuarter.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid ReportingQuarter: {err.Message}");
            #endif
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ReportingQuarter value, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (value.IsDefault)
            {
                writer.WriteNullValue();
                return;
            }
            #if NET8_0_OR_GREATER
            writer.WriteStringValue(value.Value.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
            #else
            global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
            #endif
        }
    }

}
