//HintName: ShiftTime.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(ShiftTimeJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(ShiftTimeTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{ShiftTime}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial record struct ShiftTime :
    IDomainPrimitive<ShiftTime, System.TimeOnly>,
    IParsable<ShiftTime>,
    ISpanParsable<ShiftTime>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<ShiftTime>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<ShiftTime>,
    IComparable,
    System.Numerics.IEqualityOperators<ShiftTime, ShiftTime, bool>,
    System.Numerics.IComparisonOperators<ShiftTime, ShiftTime, bool>
{
    private readonly System.TimeOnly _value;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => _value.Equals(default(System.TimeOnly));

    /// <summary>The underlying primitive value.</summary>
    public System.TimeOnly Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of ShiftTime. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "ShiftTime";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Temporal = "TEMPORAL";
        public const string Invariant = "INVARIANT";
    }

    private ShiftTime(System.TimeOnly value) => _value = value;

    // --- Validation -------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Validate(System.TimeOnly value)
    {
        var error = TryValidate(value);
        if (error.IsError)
        {
            throw new DomainPrimitiveValidationException(error);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(System.TimeOnly value)
    {
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // --- Factory Methods ---------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ShiftTime Create(System.TimeOnly value)
    {
        Validate(value);
        return new ShiftTime(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(System.TimeOnly value, out ShiftTime result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new ShiftTime(value);
        return true;
    }

    // --- Parsing -----------------------------------------------------

    public static ShiftTime Parse(string s) => Parse(s, null);
    public static ShiftTime Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for ShiftTime.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out ShiftTime result)
    {
        if (System.TimeOnly.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static ShiftTime Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out ShiftTime result)
    {
        if (System.TimeOnly.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static ShiftTime Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out ShiftTime result)
    {
        int count = System.Text.Encoding.UTF8.GetCharCount(utf8Text);
        if (count <= 512)
        {
            System.Span<char> chars = stackalloc char[count];
            System.Text.Encoding.UTF8.GetChars(utf8Text, chars);
            if (System.TimeOnly.TryParse((System.ReadOnlySpan<char>)chars, provider, out var parsed))
            {
                if (TryCreate(parsed, out result, out _)) return true;
            }
        }
        else
        {
            var rented = System.Buffers.ArrayPool<char>.Shared.Rent(count);
            try
            {
                System.Text.Encoding.UTF8.GetChars(utf8Text, rented);
                if (System.TimeOnly.TryParse((System.ReadOnlySpan<char>)rented.AsSpan(0, count), provider, out var parsed))
                {
                    if (TryCreate(parsed, out result, out _)) return true;
                }
            }
            finally
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented);
            }
        }
        result = default;
        return false;
    }
    #endif

    // --- Formatting --------------------------------------------------

    public void Deconstruct(out System.TimeOnly value) => value = _value;

    public override string ToString() => _value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
            var s = _value.ToString(format != default ? format.ToString() : null, provider);
            return System.Text.Encoding.UTF8.TryGetBytes(s.AsSpan(), utf8Destination, out bytesWritten);
    }
    #endif

    // --- Operators ----------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator System.TimeOnly(ShiftTime value) => value._value;

    public static explicit operator ShiftTime(System.TimeOnly value) => Create(value);

    // --- Comparison --------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(ShiftTime other) => _value.CompareTo(other._value);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        ShiftTime other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type ShiftTime.")
    };

    public static bool operator <(ShiftTime left, ShiftTime right) => left.CompareTo(right) < 0;
    public static bool operator <=(ShiftTime left, ShiftTime right) => left.CompareTo(right) <= 0;
    public static bool operator >(ShiftTime left, ShiftTime right) => left.CompareTo(right) > 0;
    public static bool operator >=(ShiftTime left, ShiftTime right) => left.CompareTo(right) >= 0;

    // --- TypeConverter -----------------------------------------------

    public sealed class ShiftTimeTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType) => sourceType == typeof(string) || sourceType == typeof(System.TimeOnly) || base.CanConvertFrom(context, sourceType);
        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return Parse(s, culture);
            if (value is System.TimeOnly v) return Create(v);
            return base.ConvertFrom(context, culture, value);
        }
        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType) => destinationType == typeof(string) || destinationType == typeof(System.TimeOnly) || base.CanConvertTo(context, destinationType);
        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is ShiftTime instance)
            {
                if (destinationType == typeof(string)) return instance.ToString();
                if (destinationType == typeof(System.TimeOnly)) return instance.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // --- JSON Serialization -----------------------------------------------

    private sealed class ShiftTimeJsonConverter : global::System.Text.Json.Serialization.JsonConverter<ShiftTime>
    {
        public override ShiftTime Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            var value = global::System.Text.Json.JsonSerializer.Deserialize<System.TimeOnly>(ref reader, options);
            if (ShiftTime.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid ShiftTime: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ShiftTime value, global::System.Text.Json.JsonSerializerOptions options)
        {
            global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
        }
    }

}
