//HintName: OutsideTemp.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(OutsideTempJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(OutsideTempTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{OutsideTemp}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.DebuggerTypeProxy(typeof(OutsideTempDebugView))]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial record struct OutsideTemp :
    IDomainPrimitive<OutsideTemp, double>,
    IParsable<OutsideTemp>,
    ISpanParsable<OutsideTemp>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<OutsideTemp>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<OutsideTemp>,
    IComparable,
    System.Numerics.IEqualityOperators<OutsideTemp, OutsideTemp, bool>,
System.Numerics.IComparisonOperators<OutsideTemp, OutsideTemp, bool>
{
    private readonly double _value;
    private readonly bool _isInitialized;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => !_isInitialized;

    /// <summary>The underlying primitive value.</summary>
    public double Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of OutsideTemp. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "OutsideTemp";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Range = "RANGE";
        public const string Invariant = "INVARIANT";
    }

    private OutsideTemp(double value)
    {
        _value = value;
        _isInitialized = true;
    }

    // --- Validation -------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Validate(double value)
    {
        var error = TryValidate(value);
        if (error.IsError)
        {
            throw new DomainPrimitiveValidationException(error);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(double value)
    {
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // --- Factory Methods ---------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static OutsideTemp Create(double value)
    {
        Validate(value);
        return new OutsideTemp(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(double value, out OutsideTemp result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new OutsideTemp(value);
        return true;
    }

    // --- Parsing -----------------------------------------------------

    public static OutsideTemp Parse(string s) => Parse(s, null);
    public static OutsideTemp Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for OutsideTemp.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out OutsideTemp result)
    {
        if (double.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static OutsideTemp Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out OutsideTemp result)
    {
        if (double.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static OutsideTemp Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out OutsideTemp result)
    {
        if (double.TryParse(utf8Text, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }
    #endif
    // --- Formatting --------------------------------------------------

    public void Deconstruct(out double value) => value = _value;

    public override string ToString() => _value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(utf8Destination, out bytesWritten, format, provider);
    #endif

    // --- Operators ----------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator double(OutsideTemp value) => value._value;

    public static explicit operator OutsideTemp(double value) => Create(value);

    // --- Comparison --------------------------------------------------

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(OutsideTemp other) => _value.CompareTo(other._value);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        OutsideTemp other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type OutsideTemp.")
    };

    public static bool operator <(OutsideTemp left, OutsideTemp right) => left.CompareTo(right) < 0;
    public static bool operator <=(OutsideTemp left, OutsideTemp right) => left.CompareTo(right) <= 0;
    public static bool operator >(OutsideTemp left, OutsideTemp right) => left.CompareTo(right) > 0;
    public static bool operator >=(OutsideTemp left, OutsideTemp right) => left.CompareTo(right) >= 0;

    // --- TypeConverter -----------------------------------------------

    private sealed class OutsideTempTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || sourceType == typeof(double) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return OutsideTemp.Parse(s, culture);
            if (value is double v) return OutsideTemp.Create(v);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || destinationType == typeof(double) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is OutsideTemp id)
            {
                if (destinationType == typeof(string)) return id.ToString();
                if (destinationType == typeof(double)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    private sealed class OutsideTempDebugView
    {
        private readonly OutsideTemp _t;
        public OutsideTempDebugView(OutsideTemp t) => _t = t;
        public string Value => _t.IsDefault ? "default" : _t.Value.ToString();
    }
    // --- JSON Serialization -----------------------------------------------

    private sealed class OutsideTempJsonConverter : global::System.Text.Json.Serialization.JsonConverter<OutsideTemp>
    {
        public override OutsideTemp Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            var value = global::System.Text.Json.JsonSerializer.Deserialize<double>(ref reader, options);
            if (OutsideTemp.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid OutsideTemp: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, OutsideTemp value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteNumberValue(value.Value);
        }
    }

}
