//HintName: Population.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(PopulationJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(PopulationTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{Population}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.DebuggerTypeProxy(typeof(PopulationDebugView))]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial record struct Population :
    IDomainPrimitive<Population, long>,
    IParsable<Population>,
    ISpanParsable<Population>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<Population>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<Population>,
    IComparable,
    System.Numerics.IEqualityOperators<Population, Population, bool>,
System.Numerics.IComparisonOperators<Population, Population, bool>
{
    private readonly long _value;
    private readonly bool _isInitialized;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => !_isInitialized;

    /// <summary>The underlying primitive value.</summary>
    public long Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of Population. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "Population";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Range = "RANGE";
        public const string Invariant = "INVARIANT";
    }

    private Population(long value)
    {
        _value = value;
        _isInitialized = true;
    }

    // ─── Validation ─────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Validate(long value)
    {
        var error = TryValidate(value);
        if (error.IsError)
        {
            throw new DomainPrimitiveValidationException(error);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(long value)
    {
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // ─── Factory Methods ─────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Population Create(long value)
    {
        Validate(value);
        return new Population(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(long value, out Population result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new Population(value);
        return true;
    }

    // ─── Parsing ─────────────────────────────────────────────────────

    public static Population Parse(string s) => Parse(s, null);
    public static Population Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for Population.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out Population result)
    {
        if (long.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static Population Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Population result)
    {
        if (long.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static Population Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out Population result)
    {
        if (long.TryParse(utf8Text, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }
    #endif
    // ─── Formatting ──────────────────────────────────────────────────

    public void Deconstruct(out long value) => value = _value;

    public override string ToString() => _value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(utf8Destination, out bytesWritten, format, provider);
    #endif

    // ─── Operators ────────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator long(Population value) => value._value;

    public static explicit operator Population(long value) => Create(value);

    // ─── Comparison ──────────────────────────────────────────────────

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(Population other) => _value.CompareTo(other._value);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        Population other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type Population.")
    };

    public static bool operator <(Population left, Population right) => left.CompareTo(right) < 0;
    public static bool operator <=(Population left, Population right) => left.CompareTo(right) <= 0;
    public static bool operator >(Population left, Population right) => left.CompareTo(right) > 0;
    public static bool operator >=(Population left, Population right) => left.CompareTo(right) >= 0;

    // ─── TypeConverter ───────────────────────────────────────────────

    private sealed class PopulationTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || sourceType == typeof(long) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return Population.Parse(s, culture);
            if (value is long v) return Population.Create(v);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || destinationType == typeof(long) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is Population id)
            {
                if (destinationType == typeof(string)) return id.ToString();
                if (destinationType == typeof(long)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    private sealed class PopulationDebugView
    {
        private readonly Population _t;
        public PopulationDebugView(Population t) => _t = t;
        public string Value => _t.IsDefault ? "default" : _t.Value.ToString();
    }
    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class PopulationJsonConverter : global::System.Text.Json.Serialization.JsonConverter<Population>
    {
        public override Population Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!reader.TryGetInt64(out var value)) throw new global::System.Text.Json.JsonException($"Invalid Population: expected long.");
            if (Population.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid Population: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, Population value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteNumberValue(value.Value);
        }
    }

}
