//HintName: Discount.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(DiscountJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(DiscountTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{Discount}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.DebuggerTypeProxy(typeof(DiscountDebugView))]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial record struct Discount :
    IDomainPrimitive<Discount, decimal>,
    IParsable<Discount>,
    ISpanParsable<Discount>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<Discount>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<Discount>,
    IComparable,
    System.Numerics.IEqualityOperators<Discount, Discount, bool>,
System.Numerics.IComparisonOperators<Discount, Discount, bool>
{
    private readonly decimal _value;
    private readonly bool _isInitialized;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => !_isInitialized;

    /// <summary>The underlying primitive value.</summary>
    public decimal Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of Discount. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "Discount";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Range = "RANGE";
        public const string Invariant = "INVARIANT";
    }

    private Discount(decimal value)
    {
        _value = value;
        _isInitialized = true;
    }

    // --- Validation -------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Validate(decimal value)
    {
        var error = TryValidate(value);
        if (error.IsError)
        {
            throw new DomainPrimitiveValidationException(error);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(decimal value)
    {
        if (value < (decimal)0)
            return new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("RANGE", $"Discount must be at least 0. Got {value}.");
        if (value > (decimal)100)
            return new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("RANGE", $"Discount must be at most 100. Got {value}.");
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // --- Factory Methods ---------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Discount Create(decimal value)
    {
        Validate(value);
        return new Discount(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(decimal value, out Discount result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new Discount(value);
        return true;
    }

    // --- Parsing -----------------------------------------------------

    public static Discount Parse(string s) => Parse(s, null);
    public static Discount Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for Discount.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out Discount result)
    {
        if (decimal.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static Discount Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Discount result)
    {
        if (decimal.TryParse(s, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static Discount Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out Discount result)
    {
        if (decimal.TryParse(utf8Text, provider, out var parsed))
        {
            if (TryCreate(parsed, out result, out _)) return true;
        }
        result = default;
        return false;
    }
    #endif
    // --- Formatting --------------------------------------------------

    public void Deconstruct(out decimal value) => value = _value;

    public override string ToString() => _value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(utf8Destination, out bytesWritten, format, provider);
    #endif

    // --- Operators ----------------------------------------------------

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator decimal(Discount value) => value._value;

    public static explicit operator Discount(decimal value) => Create(value);

    // --- Comparison --------------------------------------------------

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(Discount other) => _value.CompareTo(other._value);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        Discount other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type Discount.")
    };

    public static bool operator <(Discount left, Discount right) => left.CompareTo(right) < 0;
    public static bool operator <=(Discount left, Discount right) => left.CompareTo(right) <= 0;
    public static bool operator >(Discount left, Discount right) => left.CompareTo(right) > 0;
    public static bool operator >=(Discount left, Discount right) => left.CompareTo(right) >= 0;

    // --- TypeConverter -----------------------------------------------

    private sealed class DiscountTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || sourceType == typeof(decimal) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return Discount.Parse(s, culture);
            if (value is decimal v) return Discount.Create(v);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || destinationType == typeof(decimal) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is Discount id)
            {
                if (destinationType == typeof(string)) return id.ToString();
                if (destinationType == typeof(decimal)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    private sealed class DiscountDebugView
    {
        private readonly Discount _t;
        public DiscountDebugView(Discount t) => _t = t;
        public string Value => _t.IsDefault ? "default" : _t.Value.ToString();
    }
    // --- JSON Serialization -----------------------------------------------

    private sealed class DiscountJsonConverter : global::System.Text.Json.Serialization.JsonConverter<Discount>
    {
        public override Discount Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!reader.TryGetDecimal(out var value)) throw new global::System.Text.Json.JsonException($"Invalid Discount: expected decimal.");
            if (Discount.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid Discount: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, Discount value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteNumberValue(value.Value);
        }
    }

}
