//HintName: OrderStatus.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(OrderStatusJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(OrderStatusTypeConverter))]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Diagnostics.DebuggerDisplay("{OrderStatus}({Name})")]
readonly partial record struct OrderStatus : 
    EricksonLopez.DomainPrimitives.IDomainPrimitive<OrderStatus, int>,
    IEquatable<OrderStatus>,
    IParsable<OrderStatus>,
    IFormattable,
    ISpanFormattable
{
    public int Value { get; }
    public string Name { get; }
    public bool IsDefault => Name is null;

    private OrderStatus(int value, string name)
    {
        Value = value;
        Name = name;
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "OrderStatus";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Range = "RANGE";
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static OrderStatus Create(int value) => FromValue(value);
    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(int value, out OrderStatus result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        var success = TryFromValue(value, out result);
        validationError = success ? global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None : new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("RANGE", $"Value {value} is not a valid {PrimitiveName}.");
        return success;
    }

    public static readonly IReadOnlyList<OrderStatus> All = new OrderStatus[] { Pending, Processing };

    public static bool TryFromValue(int value, out OrderStatus result)
    {
        foreach (var item in All)
        {
            if (EqualityComparer<int>.Default.Equals(item.Value, value))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    public static OrderStatus FromValue(int value)
    {
        if (TryFromValue(value, out var result)) return result;
        throw new ArgumentException($"No OrderStatus found with value {value}", nameof(value));
    }

    public static bool TryFromName(string name, out OrderStatus result)
    {
        foreach (var item in All)
        {
            if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    /// <summary>Tries to get a member by name, optionally ignoring case.</summary>
    public static bool TryFromName(string name, bool ignoreCase, out OrderStatus result)
    {
        var comparison = ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
        foreach (var item in All)
        {
            if (string.Equals(item.Name, name, comparison))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    public static OrderStatus FromName(string name)
    {
        if (TryFromName(name, out var result)) return result;
        throw new ArgumentException($"No OrderStatus found with name {name}", nameof(name));
    }

    /// <summary>Exhaustively matches this OrderStatus against all known members.</summary>
    public TResult Match<TResult>(Func<TResult> whenPending, Func<TResult> whenProcessing)
    {
        if (Equals(Pending)) return whenPending();
        if (Equals(Processing)) return whenProcessing();
        throw new InvalidOperationException($"Unknown OrderStatus member: {Name}");
    }

    /// <summary>Exhaustively maps this OrderStatus to a result, passing the member as argument to each case.</summary>
    public TResult Map<TResult>(Func<OrderStatus, TResult> whenPending, Func<OrderStatus, TResult> whenProcessing)
    {
        if (Equals(Pending)) return whenPending(this);
        if (Equals(Processing)) return whenProcessing(this);
        throw new InvalidOperationException($"Unknown OrderStatus member: {Name}");
    }

    /// <summary>Exhaustively executes an action for each known member of OrderStatus.</summary>
    public void Switch(Action whenPending, Action whenProcessing)
    {
        if (Equals(Pending)) { whenPending(); return; }
        if (Equals(Processing)) { whenProcessing(); return; }
        throw new InvalidOperationException($"Unknown OrderStatus member: {Name}");
    }

    public override string ToString() => Name;
    public string ToString(string? format, IFormatProvider? formatProvider) => Name;
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        var nameSpan = Name.AsSpan();
        if (nameSpan.Length <= destination.Length)
        {
            nameSpan.CopyTo(destination);
            charsWritten = nameSpan.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    public static OrderStatus Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new global::System.FormatException($"The value '{s}' is not valid for OrderStatus.");
    }
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out OrderStatus result)
    {
        if (s is null)
        {
            result = default;
            return false;
        }
        return TryFromName(s, out result);
    }

    public bool Equals(OrderStatus other)
    {
        return EqualityComparer<int>.Default.Equals(Value, other.Value);
    }

    public override int GetHashCode()
    {
        return EqualityComparer<int>.Default.GetHashCode(Value);
    }
    // ─── TypeConverter ───────────────────────────────────────────────

    private sealed class OrderStatusTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || sourceType == typeof(int) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return OrderStatus.Parse(s, culture);
            if (value is int v) return OrderStatus.Create(v);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || destinationType == typeof(int) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is OrderStatus id)
            {
                if (destinationType == typeof(string)) return id.ToString();
                if (destinationType == typeof(int)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class OrderStatusJsonConverter : global::System.Text.Json.Serialization.JsonConverter<OrderStatus>
    {
        public override OrderStatus Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!reader.TryGetInt32(out var value)) throw new global::System.Text.Json.JsonException($"Invalid OrderStatus: expected int.");
            if (OrderStatus.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid OrderStatus: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, OrderStatus value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteNumberValue(value.Value);
        }
    }

}

