//HintName: NestedPrimitive.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
#if NET8_0_OR_GREATER
using System.Collections.Frozen;
#endif
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(NestedPrimitiveJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(NestedPrimitiveTypeConverter))]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Diagnostics.DebuggerStepThrough]
[global::System.Diagnostics.DebuggerDisplay("{NestedPrimitive}({Name})")]
readonly partial record struct NestedPrimitive : 
    EricksonLopez.DomainPrimitives.IDomainPrimitive<NestedPrimitive, int>,
    IEquatable<NestedPrimitive>,
    IParsable<NestedPrimitive>,
    IFormattable,
    ISpanFormattable
{
    private readonly int _value;
    public string Name { get; }
    public bool IsDefault => Name is null;

    /// <summary>The underlying primitive value.</summary>
    public int Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of NestedPrimitive. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    private NestedPrimitive(int value, string name)
    {
        _value = value;
        Name = name;
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "NestedPrimitive";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Range = "RANGE";
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static NestedPrimitive Create(int value) => FromValue(value);
    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(int value, out NestedPrimitive result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        var success = TryFromValue(value, out result);
        validationError = success ? global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None : new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("RANGE", $"The provided value is not a valid {PrimitiveName}.");
        return success;
    }

    /// <summary>Returns all defined members of <see cref="NestedPrimitive"/>. This type has no declared members — the list is empty.</summary>
    public static readonly global::System.Collections.Generic.IReadOnlyList<NestedPrimitive> All = global::System.Array.AsReadOnly(global::System.Array.Empty<NestedPrimitive>());

    #if NET8_0_OR_GREATER
    private static readonly global::System.Collections.Frozen.FrozenDictionary<int, NestedPrimitive> _byValue =
        All.ToFrozenDictionary(x => x.Value);
    private static readonly global::System.Collections.Frozen.FrozenDictionary<string, NestedPrimitive> _byName =
        All.ToFrozenDictionary(x => x.Name, global::System.StringComparer.OrdinalIgnoreCase);
    #endif

    public static bool TryFromValue(int value, out NestedPrimitive result)
    {
        #if NET8_0_OR_GREATER
        return _byValue.TryGetValue(value, out result);
        #else
        foreach (var item in All)
        {
            if (EqualityComparer<int>.Default.Equals(item.Value, value))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
        #endif
    }

    public static NestedPrimitive FromValue(int value)
    {
        if (TryFromValue(value, out var result)) return result;
        throw new ArgumentException($"No NestedPrimitive found with value {value}", nameof(value));
    }

    public static bool TryFromName(string name, out NestedPrimitive result)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            result = default;
            return false;
        }
        #if NET8_0_OR_GREATER
        return _byName.TryGetValue(name, out result);
        #else
        foreach (var item in All)
        {
            if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
        #endif
    }

    /// <summary>Tries to get a member by name, optionally ignoring case.</summary>
    public static bool TryFromName(string name, bool ignoreCase, out NestedPrimitive result)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            result = default;
            return false;
        }
        #if NET8_0_OR_GREATER
        // FrozenDictionary: ignoreCase=true uses OrdinalIgnoreCase dict (always); ignoreCase=false falls through to Ordinal linear scan.
        if (ignoreCase) return _byName.TryGetValue(name, out result);
        #endif
        var comparison = ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
        foreach (var item in All)
        {
            if (string.Equals(item.Name, name, comparison))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    public static NestedPrimitive FromName(string name, bool ignoreCase = false)
    {
        if (TryFromName(name, ignoreCase, out var result)) return result;
        throw new ArgumentException($"No NestedPrimitive found with name {name}", nameof(name));
    }

    public override string ToString() => Name ?? string.Empty;
    public string ToString(string? format, IFormatProvider? formatProvider) => Name ?? string.Empty;
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        var nameSpan = (Name ?? string.Empty).AsSpan();
        if (nameSpan.Length <= destination.Length)
        {
            nameSpan.CopyTo(destination);
            charsWritten = nameSpan.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    public static NestedPrimitive Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new global::System.FormatException($"The value '{s}' is not valid for NestedPrimitive.");
    }
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out NestedPrimitive result)
    {
        if (s is null)
        {
            result = default;
            return false;
        }
        return TryFromName(s, out result);
    }

    public bool Equals(NestedPrimitive other)
    {
        if (IsDefault || other.IsDefault) return IsDefault == other.IsDefault;
        return EqualityComparer<int>.Default.Equals(_value, other._value);
    }

    public override int GetHashCode()
    {
        if (IsDefault) return 0;
        return EqualityComparer<int>.Default.GetHashCode(_value);
    }
    // ─── TypeConverter ───────────────────────────────────────────────

    private sealed class NestedPrimitiveTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || sourceType == typeof(int) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return NestedPrimitive.Parse(s, culture);
            if (value is int v) return NestedPrimitive.Create(v);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || destinationType == typeof(int) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is NestedPrimitive id)
            {
                if (destinationType == typeof(string)) return id.ToString();
                if (destinationType == typeof(int)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class NestedPrimitiveJsonConverter : global::System.Text.Json.Serialization.JsonConverter<NestedPrimitive>
    {
        public override NestedPrimitive Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) return default;

            if (!reader.TryGetInt32(out var value)) throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: expected int.");
            if (NestedPrimitive.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, NestedPrimitive value, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (value.IsDefault)
            {
                writer.WriteNullValue();
                return;
            }
            writer.WriteNumberValue(value.Value);
        }
    }

}

