//HintName: Role.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(RoleJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(RoleTypeConverter))]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Diagnostics.DebuggerDisplay("{Role}({Name})")]
readonly partial record struct Role : 
    EricksonLopez.DomainPrimitives.IDomainPrimitive<Role, string>,
    IEquatable<Role>,
    IParsable<Role>,
    IFormattable,
    ISpanFormattable
{
    public string Value { get; }
    public string Name { get; }
    public bool IsDefault => Name is null;

    private Role(string value, string name)
    {
        Value = value;
        Name = name;
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "Role";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Range = "RANGE";
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Role Create(string value) => FromValue(value);
    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(string value, out Role result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        var success = TryFromValue(value, out result);
        validationError = success ? global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None : new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("RANGE", $"Value {value} is not a valid {PrimitiveName}.");
        return success;
    }

    public static readonly IReadOnlyList<Role> All = new Role[] { Admin, User };

    public static bool TryFromValue(string value, out Role result)
    {
        foreach (var item in All)
        {
            if (item.Value is not null && item.Value.Equals(value))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    public static Role FromValue(string value)
    {
        if (TryFromValue(value, out var result)) return result;
        throw new ArgumentException($"No Role found with value {value}", nameof(value));
    }

    public static bool TryFromName(string name, out Role result)
    {
        foreach (var item in All)
        {
            if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    /// <summary>Tries to get a member by name, optionally ignoring case.</summary>
    public static bool TryFromName(string name, bool ignoreCase, out Role result)
    {
        var comparison = ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
        foreach (var item in All)
        {
            if (string.Equals(item.Name, name, comparison))
            {
                result = item;
                return true;
            }
        }
        result = default;
        return false;
    }

    public static Role FromName(string name)
    {
        if (TryFromName(name, out var result)) return result;
        throw new ArgumentException($"No Role found with name {name}", nameof(name));
    }

    /// <summary>Exhaustively matches this Role against all known members.</summary>
    public TResult Match<TResult>(Func<TResult> whenAdmin, Func<TResult> whenUser)
    {
        if (Equals(Admin)) return whenAdmin();
        if (Equals(User)) return whenUser();
        throw new InvalidOperationException($"Unknown Role member: {Name}");
    }

    /// <summary>Exhaustively maps this Role to a result, passing the member as argument to each case.</summary>
    public TResult Map<TResult>(Func<Role, TResult> whenAdmin, Func<Role, TResult> whenUser)
    {
        if (Equals(Admin)) return whenAdmin(this);
        if (Equals(User)) return whenUser(this);
        throw new InvalidOperationException($"Unknown Role member: {Name}");
    }

    /// <summary>Exhaustively executes an action for each known member of Role.</summary>
    public void Switch(Action whenAdmin, Action whenUser)
    {
        if (Equals(Admin)) { whenAdmin(); return; }
        if (Equals(User)) { whenUser(); return; }
        throw new InvalidOperationException($"Unknown Role member: {Name}");
    }

    public override string ToString() => Name;
    public string ToString(string? format, IFormatProvider? formatProvider) => Name;
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        var nameSpan = Name.AsSpan();
        if (nameSpan.Length <= destination.Length)
        {
            nameSpan.CopyTo(destination);
            charsWritten = nameSpan.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    public static Role Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new global::System.FormatException($"The value '{s}' is not valid for Role.");
    }
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out Role result)
    {
        if (s is null)
        {
            result = default;
            return false;
        }
        return TryFromName(s, out result);
    }

    public bool Equals(Role other)
    {
        return Value is not null ? Value.Equals(other.Value) : other.Value is null;
    }

    public override int GetHashCode()
    {
        return Value is not null ? Value.GetHashCode() : 0;
    }
    // --- TypeConverter -----------------------------------------------

    private sealed class RoleTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return Role.Create(s);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is Role id)
            {
                if (destinationType == typeof(string)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // --- JSON Serialization -----------------------------------------------

    private sealed class RoleJsonConverter : global::System.Text.Json.Serialization.JsonConverter<Role>
    {
        public override Role Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            #if NET8_0_OR_GREATER
            // Hot path: zero-allocation via ValueSpan (only fires when HasValueSequence=false).
            if (!reader.HasValueSequence)
            {
                if (Role.TryParse(reader.ValueSpan, null, out var spanResult)) return spanResult;
                throw new global::System.Text.Json.JsonException($"Invalid Role: unable to parse value.");
            }
            // Rare fallback: value spans multiple segments (>16KB JSON string). Accepts one allocation.
            var stringValue = reader.GetString();
            if (stringValue is null) return default;
            if (Role.TryCreate(stringValue, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid Role: {err.Message}");
            #else
            // Fallback for older TFMs: allocates a string.
            var stringValue = reader.GetString();
            if (stringValue is null) return default;
            if (Role.TryCreate(stringValue, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid Role: {err.Message}");
            #endif
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, Role value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.Value);
        }
    }

}

