//HintName: NestedPrimitive.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(NestedPrimitiveJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(NestedPrimitiveTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{NestedPrimitive}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.DebuggerTypeProxy(typeof(NestedPrimitiveDebugView))]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial record struct NestedPrimitive :
    IDomainPrimitive<NestedPrimitive, string>,
    IParsable<NestedPrimitive>,
    ISpanParsable<NestedPrimitive>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<NestedPrimitive>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<NestedPrimitive>,
    IComparable,
    System.Numerics.IEqualityOperators<NestedPrimitive, NestedPrimitive, bool>,
    System.Numerics.IComparisonOperators<NestedPrimitive, NestedPrimitive, bool>
{
    private readonly string _value;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => _value is null;

    /// <summary>The underlying string value.</summary>
    public string Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_value is null) throw new InvalidOperationException($"Value accessed on a default instance of NestedPrimitive. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "NestedPrimitive";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Empty = "EMPTY";
        public const string Length = "LENGTH";
        public const string Format = "FORMAT";
        public const string Invariant = "INVARIANT";
    }

    private NestedPrimitive(string value) => _value = value;

    // ─── Normalization ───────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static string Normalize(string value)
    {
        value = value.Normalize(System.Text.NormalizationForm.FormC);
        return value;
    }

    // ─── Validation ─────────────────────────────────────────────────

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Validate(string value)
    {
        var error = TryValidate(value);
        if (error.IsError)
        {
            throw new DomainPrimitiveValidationException(error);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidate(string value)
    {
        if (value.Length > 4096)
            return new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("LENGTH", $"NestedPrimitive must be at most 4096 character(s) (security limit). Got {value.Length}.");
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // ─── Factory Methods ─────────────────────────────────────────────

    /// <summary>Creates a valid instance. Normalizes, then validates. Throws on invalid input.</summary>
    /// <exception cref="ArgumentNullException">Thrown when the value is null.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static NestedPrimitive Create(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        value = Normalize(value);
        Validate(value);
        return new NestedPrimitive(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(string value, out NestedPrimitive result, out global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError validationError)
    {
        if (value is null)
        {
            result = default;
            validationError = new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("NULL_INPUT", "Value cannot be null.");
            return false;
        }
        value = Normalize(value);
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new NestedPrimitive(value);
        return true;
    }

    /// <summary>Validates a pre-NFC-normalized span. Caller must ensure the span is already in NFC form.</summary>
    private static global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError TryValidateSpan(ReadOnlySpan<char> value)
    {
        if (value.Length > 4096)
            return new global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError("LENGTH", $"NestedPrimitive must be at most 4096 character(s) (security limit). Got {value.Length}.");
        return global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
    }

    // ─── Parsing (IParsable, ISpanParsable, IUtf8SpanParsable) ───────

    public static NestedPrimitive Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for NestedPrimitive.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (s is not null)
        {
            if (TryCreate(s, out result, out _)) return true;
        }
        result = default;
        return false;
    }

    public static NestedPrimitive Parse(ReadOnlySpan<char> s, IFormatProvider? provider)
    {
        var normalized = s.ToString().Normalize(System.Text.NormalizationForm.FormC);
        var error = TryValidateSpan(normalized.AsSpan());
        if (error.IsError) throw new System.FormatException(error.Message);
        return new NestedPrimitive(normalized);
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out NestedPrimitive result)
    {
        var normalized = s.ToString().Normalize(System.Text.NormalizationForm.FormC);
        var error = TryValidateSpan(normalized.AsSpan());
        if (error.IsError)
        {
            result = default;
            return false;
        }
        result = new NestedPrimitive(normalized);
        return true;
    }

    #if NET8_0_OR_GREATER
    public static NestedPrimitive Parse(ReadOnlySpan<byte> utf8, IFormatProvider? provider)
    {
        // TD-003: Use GetMaxCharCount (O(1)) for the size guard — no traversal needed.
        // The real char count comes from GetChars() which returns the exact decoded length.
        int maxCount = System.Text.Encoding.UTF8.GetMaxCharCount(utf8.Length);
        // Stackalloc limit is 256 chars = 512 bytes on stack — safe for typical domain values.
        if (maxCount <= 256)
        {
            Span<char> chars = stackalloc char[maxCount];
            int count = System.Text.Encoding.UTF8.GetChars(utf8, chars);
            return Parse(chars.Slice(0, count), provider);
        }
        else
        {
            var rented = System.Buffers.ArrayPool<char>.Shared.Rent(maxCount);
            try
            {
                int count = System.Text.Encoding.UTF8.GetChars(utf8, rented);
                return Parse(rented.AsSpan(0, count), provider);
            }
            finally
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented);
            }
        }
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8, IFormatProvider? provider, out NestedPrimitive result)
    {
        int maxCount = System.Text.Encoding.UTF8.GetMaxCharCount(utf8.Length);
        if (maxCount <= 256)
        {
            Span<char> chars = stackalloc char[maxCount];
            int count = System.Text.Encoding.UTF8.GetChars(utf8, chars);
            return TryParse(chars.Slice(0, count), provider, out result);
        }
        else
        {
            var rented = System.Buffers.ArrayPool<char>.Shared.Rent(maxCount);
            try
            {
                int count = System.Text.Encoding.UTF8.GetChars(utf8, rented);
                return TryParse(rented.AsSpan(0, count), provider, out result);
            }
            finally
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented);
            }
        }
    }
    #endif

    // ─── Formatting (IFormattable, ISpanFormattable, IUtf8SpanFormattable) ───

    public void Deconstruct(out string value) => value = _value;

    public override string ToString() => _value ?? string.Empty;

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value ?? string.Empty;

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        if (_value is null) { charsWritten = 0; return false; }
        var v = _value.AsSpan();
        if (v.TryCopyTo(destination))
        {
            charsWritten = v.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        if (_value is null) { bytesWritten = 0; return false; }
        return System.Text.Encoding.UTF8.TryGetBytes(_value.AsSpan(), utf8Destination, out bytesWritten);
    }
    #endif

    // ─── Operators ────────────────────────────────────────────────────

    /// <summary>Explicit conversion to string.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator string(NestedPrimitive value) =>
        value._value ?? throw new InvalidOperationException("Cannot convert a default NestedPrimitive to string. Check IsDefault before casting.");

    /// <summary>Explicit conversion from string. Applies normalization and validation.</summary>
    public static explicit operator NestedPrimitive(string value) => Create(value);

    // ─── Comparison ──────────────────────────────────────────────────

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(NestedPrimitive other) => string.Compare(_value, other._value, StringComparison.Ordinal);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        NestedPrimitive other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type NestedPrimitive.")
    };

    public static bool operator <(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) < 0;
    public static bool operator <=(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) <= 0;
    public static bool operator >(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) > 0;
    public static bool operator >=(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) >= 0;

    // ─── TypeConverter ───────────────────────────────────────────────

    private sealed class NestedPrimitiveTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return NestedPrimitive.Create(s);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is NestedPrimitive id)
            {
                if (destinationType == typeof(string)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    private sealed class NestedPrimitiveDebugView
    {
        private readonly NestedPrimitive _t;
        public NestedPrimitiveDebugView(NestedPrimitive t) => _t = t;
        public string Value => _t.IsDefault ? "default" : _t.Value;
    }
    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class NestedPrimitiveJsonConverter : global::System.Text.Json.Serialization.JsonConverter<NestedPrimitive>
    {
        public override NestedPrimitive Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            #if NET8_0_OR_GREATER
            // Hot path: zero-allocation via ValueSpan (only fires when HasValueSequence=false).
            if (!reader.HasValueSequence)
            {
                if (NestedPrimitive.TryParse(reader.ValueSpan, null, out var spanResult)) return spanResult;
                throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: unable to parse value.");
            }
            // Rare fallback: value spans multiple segments (>16KB JSON string). Accepts one allocation.
            var stringValue = reader.GetString();
            if (stringValue is null) return default;
            if (NestedPrimitive.TryCreate(stringValue, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: {err.Message}");
            #else
            // Fallback for older TFMs: allocates a string.
            var stringValue = reader.GetString();
            if (stringValue is null) return default;
            if (NestedPrimitive.TryCreate(stringValue, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: {err.Message}");
            #endif
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, NestedPrimitive value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.Value);
        }
    }

}
