//HintName: UserId.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(UserIdJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(UserIdTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{UserId}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.DebuggerTypeProxy(typeof(UserIdDebugView))]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public readonly partial record struct UserId :
    IStrongId<UserId, string>,
    IParsable<UserId>,
    ISpanParsable<UserId>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<UserId>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<UserId>,
    IComparable,
    System.Numerics.IEqualityOperators<UserId, UserId, bool>,
    System.Numerics.IComparisonOperators<UserId, UserId, bool>
{
    private readonly string _value;
    private readonly bool _isInitialized;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => !_isInitialized;

    /// <summary>The underlying primitive value.</summary>
    public string Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of UserId. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "UserId";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Empty = "EMPTY";
        public const string Format = "FORMAT";
    }

    private UserId(string value)
    {
        _value = value;
        _isInitialized = true;
    }

    // --- Factory Methods ---------------------------------------------

    /// <summary>Not supported for string-backed IDs. Use Create(value) with a known value.</summary>
    public static UserId Create() => throw new NotSupportedException("Cannot generate a new UserId. String-backed IDs must be assigned explicitly.");

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static PrimitiveError TryValidate(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return new PrimitiveError("EMPTY", "UserId must not be empty.");
        return PrimitiveError.None;
    }

    /// <summary>Creates a strong ID from an existing value.</summary>
    /// <exception cref="ArgumentNullException">Thrown when the value is null.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static UserId Create(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        var error = TryValidate(value);
        if (error.IsError)
            throw new DomainPrimitiveValidationException(error);
        return new(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(string value, out UserId result, out PrimitiveError validationError)
    {
        if (value is null)
        {
            result = default;
            validationError = new PrimitiveError("NULL_INPUT", "Value cannot be null.");
            return false;
        }
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new UserId(value);
        return true;
    }

    /// <summary>The empty/uninitialized sentinel.</summary>
    public static UserId Empty { get => default; }

    // --- Parsing (IParsable, ISpanParsable, IUtf8SpanParsable) -------

    public static UserId Parse(string s) => Parse(s, null);
    public static UserId Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for UserId.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out UserId result)
    {
        if (s is not null)
        {
            result = new UserId(s);
            return true;
        }
        result = default;
        return false;
    }

    public static UserId Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out UserId result)
    {
        var parsed = s.ToString();
        if (parsed.Length > 0)
        {
            result = new UserId(parsed);
            return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static UserId Parse(ReadOnlySpan<byte> utf8, IFormatProvider? provider = null)
    {
        if (TryParse(utf8, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8, IFormatProvider? provider, out UserId result)
    {
        int count = System.Text.Encoding.UTF8.GetCharCount(utf8);
        if (count <= 512)
        {
            System.Span<char> chars = stackalloc char[count];
            System.Text.Encoding.UTF8.GetChars(utf8, chars);
            return TryParse((System.ReadOnlySpan<char>)chars, provider, out result);
        }
        else
        {
            var rented = System.Buffers.ArrayPool<char>.Shared.Rent(count);
            try
            {
                System.Text.Encoding.UTF8.GetChars(utf8, rented);
                return TryParse(rented.AsSpan(0, count), provider, out result);
            }
            finally
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented);
            }
        }
    }
    #endif

    // --- Formatting (IFormattable, ISpanFormattable, IUtf8SpanFormattable) ---

    public void Deconstruct(out string value) => value = _value;

    public override string ToString() => _value.ToString()!;

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString();

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        if (_value is null) { charsWritten = 0; return false; }
        if (_value.AsSpan().TryCopyTo(destination))
        {
            charsWritten = _value.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        if (_value is null) { bytesWritten = 0; return false; }
        return System.Text.Encoding.UTF8.TryGetBytes(_value.AsSpan(), utf8Destination, out bytesWritten);
    }
    #endif

    // --- Operators ----------------------------------------------------

    /// <summary>Explicit conversion to the backing type.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator string(UserId id) =>
        id._value ?? throw new InvalidOperationException("Cannot convert a default UserId to string. Check IsDefault before casting.");

    /// <summary>Explicit conversion from the backing type.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator UserId(string value) => new(value);

    // --- Comparison --------------------------------------------------

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(UserId other) => string.Compare(_value, other._value, StringComparison.Ordinal);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        UserId other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type UserId.")
    };

    public static bool operator <(UserId left, UserId right) => left.CompareTo(right) < 0;
    public static bool operator <=(UserId left, UserId right) => left.CompareTo(right) <= 0;
    public static bool operator >(UserId left, UserId right) => left.CompareTo(right) > 0;
    public static bool operator >=(UserId left, UserId right) => left.CompareTo(right) >= 0;

    // --- TypeConverter -----------------------------------------------

    private sealed class UserIdTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return UserId.Create(s);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is UserId id)
            {
                if (destinationType == typeof(string)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    private sealed class UserIdDebugView
    {
        private readonly UserId _t;
        public UserIdDebugView(UserId t) => _t = t;
        public string Value => _t.IsDefault ? "default" : _t.Value.ToString();
    }
    // --- JSON Serialization -----------------------------------------------

    private sealed class UserIdJsonConverter : global::System.Text.Json.Serialization.JsonConverter<UserId>
    {
        public override UserId Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            #if NET8_0_OR_GREATER
            // Hot path: zero-allocation via ValueSpan (only fires when HasValueSequence=false).
            if (!reader.HasValueSequence)
            {
                if (UserId.TryParse(reader.ValueSpan, null, out var spanResult)) return spanResult;
                throw new global::System.Text.Json.JsonException($"Invalid UserId: unable to parse value.");
            }
            // Rare fallback: value spans multiple segments (>16KB JSON string). Accepts one allocation.
            var stringValue = reader.GetString();
            if (stringValue is null) return default;
            if (UserId.TryCreate(stringValue, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid UserId: {err.Message}");
            #else
            // Fallback for older TFMs: allocates a string.
            var stringValue = reader.GetString();
            if (stringValue is null) return default;
            if (UserId.TryCreate(stringValue, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid UserId: {err.Message}");
            #endif
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, UserId value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.Value);
        }
    }

}
