//HintName: NestedPrimitive.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Text.Json.Serialization.JsonConverter(typeof(NestedPrimitiveJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(NestedPrimitiveTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{NestedPrimitive}({IsDefault ? \"<default>\" : _value})")]
[global::System.Diagnostics.DebuggerTypeProxy(typeof(NestedPrimitiveDebugView))]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public readonly partial record struct NestedPrimitive :
    IStrongId<NestedPrimitive, int>,
    IParsable<NestedPrimitive>,
    ISpanParsable<NestedPrimitive>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<NestedPrimitive>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    IComparable<NestedPrimitive>,
    IComparable,
    System.Numerics.IEqualityOperators<NestedPrimitive, NestedPrimitive, bool>,
    System.Numerics.IComparisonOperators<NestedPrimitive, NestedPrimitive, bool>
{
    private readonly int _value;
    private readonly bool _isInitialized;

    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => !_isInitialized;

    /// <summary>The underlying primitive value.</summary>
    public int Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (IsDefault) throw new InvalidOperationException($"Value accessed on a default instance of NestedPrimitive. Check IsDefault before accessing Value.");
            return _value;
        }
    }

    /// <inheritdoc/>
    public static string PrimitiveName => "NestedPrimitive";

    /// <summary>Canonical error codes for this primitive.</summary>
    public static class Errors
    {
        public const string NullInput = "NULL_INPUT";
        public const string Empty = "EMPTY";
        public const string Format = "FORMAT";
    }

    private NestedPrimitive(int value)
    {
        _value = value;
        _isInitialized = true;
    }

    // ─── Factory Methods ─────────────────────────────────────────────

    /// <summary>Not supported for integer-backed IDs. Use Create(value) with a known value.</summary>
    public static NestedPrimitive Create() => throw new NotSupportedException("Cannot generate a new NestedPrimitive. Integer-backed IDs must be assigned by the persistence layer.");

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static PrimitiveError TryValidate(int value)
    {
        if (value == 0)
            return new PrimitiveError("EMPTY", "NestedPrimitive must not be empty.");
        return PrimitiveError.None;
    }

    /// <summary>Creates a strong ID from an existing value.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static NestedPrimitive Create(int value)
    {
        var error = TryValidate(value);
        if (error.IsError)
            throw new DomainPrimitiveValidationException(error);
        return new(value);
    }

    /// <summary>Tries to create a valid instance. Returns a boolean indicating success.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryCreate(int value, out NestedPrimitive result, out PrimitiveError validationError)
    {
        validationError = TryValidate(value);
        if (validationError.IsError)
        {
            result = default;
            return false;
        }
        result = new NestedPrimitive(value);
        return true;
    }

    /// <summary>The empty/uninitialized sentinel.</summary>
    public static NestedPrimitive Empty { get => default; }

    // ─── Parsing (IParsable, ISpanParsable, IUtf8SpanParsable) ───────

    public static NestedPrimitive Parse(string s) => Parse(s, null);
    public static NestedPrimitive Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for NestedPrimitive.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (int.TryParse(s, provider, out var parsed))
        {
            result = new NestedPrimitive(parsed);
            return true;
        }
        result = default;
        return false;
    }

    public static NestedPrimitive Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (int.TryParse(s, provider, out var parsed))
        {
            result = new NestedPrimitive(parsed);
            return true;
        }
        result = default;
        return false;
    }

    #if NET8_0_OR_GREATER
    public static NestedPrimitive Parse(ReadOnlySpan<byte> utf8, IFormatProvider? provider = null)
    {
        if (TryParse(utf8, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (int.TryParse(utf8, provider, out var parsed))
        {
            result = new NestedPrimitive(parsed);
            return true;
        }
        result = default;
        return false;
    }
    #endif

    // ─── Formatting (IFormattable, ISpanFormattable, IUtf8SpanFormattable) ───

    public void Deconstruct(out int value) => value = _value;

    public override string ToString() => _value.ToString()!;

    public string ToString(string? format, IFormatProvider? formatProvider)
        => _value.ToString(format, formatProvider);

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(destination, out charsWritten, format, provider);

    #if NET8_0_OR_GREATER
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
        => _value.TryFormat(utf8Destination, out bytesWritten, format, provider);
    #endif

    // ─── Operators ────────────────────────────────────────────────────

    /// <summary>Explicit conversion to the backing type.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator int(NestedPrimitive id) => id._value;

    /// <summary>Explicit conversion from the backing type.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static explicit operator NestedPrimitive(int value) => new(value);

    // ─── Comparison ──────────────────────────────────────────────────

    /// <summary>
    /// Compares this instance with another. Default instances order before non-default instances.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int CompareTo(NestedPrimitive other) => _value.CompareTo(other._value);

    public int CompareTo(object? obj) => obj switch
    {
        null => 1,
        NestedPrimitive other => CompareTo(other),
        _ => throw new ArgumentException($"Object must be of type NestedPrimitive.")
    };

    public static bool operator <(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) < 0;
    public static bool operator <=(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) <= 0;
    public static bool operator >(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) > 0;
    public static bool operator >=(NestedPrimitive left, NestedPrimitive right) => left.CompareTo(right) >= 0;

    // ─── TypeConverter ───────────────────────────────────────────────

    private sealed class NestedPrimitiveTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || sourceType == typeof(int) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s) return NestedPrimitive.Parse(s, culture);
            if (value is int v) return NestedPrimitive.Create(v);
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || destinationType == typeof(int) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is NestedPrimitive id)
            {
                if (destinationType == typeof(string)) return id.ToString();
                if (destinationType == typeof(int)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    private sealed class NestedPrimitiveDebugView
    {
        private readonly NestedPrimitive _t;
        public NestedPrimitiveDebugView(NestedPrimitive t) => _t = t;
        public string Value => _t.IsDefault ? "default" : _t.Value.ToString();
    }
    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class NestedPrimitiveJsonConverter : global::System.Text.Json.Serialization.JsonConverter<NestedPrimitive>
    {
        public override NestedPrimitive Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!reader.TryGetInt32(out var value)) throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: expected int.");
            if (NestedPrimitive.TryCreate(value, out var result, out var err)) return result;
            throw new global::System.Text.Json.JsonException($"Invalid NestedPrimitive: {err.Message}");
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, NestedPrimitive value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteNumberValue(value.Value);
        }
    }

}
