//HintName: NestedPrimitive.g.cs
// <auto-generated/>
// Tool: EricksonLopez.DomainPrimitives.Generators
#nullable enable

using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Text.Json.Serialization.JsonConverter(typeof(NestedPrimitiveJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(NestedPrimitiveTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{NestedPrimitive}({IsDefault ? \"<default>\" : ToString()})")]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public readonly partial record struct NestedPrimitive :
    IDomainPrimitive<NestedPrimitive>,
    IFormattable,
    ISpanFormattable,
    System.Numerics.IEqualityOperators<NestedPrimitive, NestedPrimitive, bool>
{
    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => true;

    #if NET7_0_OR_GREATER
    /// <inheritdoc/>
    public static string PrimitiveName => "NestedPrimitive";
    #endif

    /// <summary>Canonical error codes for this value object.</summary>
    public static class Errors
    {
        /// <summary>Error code for null input.</summary>
        public const string NullInput = "NULL_INPUT";
        /// <summary>Error code for invariant violation (cross-property validation failure).</summary>
        public const string Invariant = "INVARIANT";
    }

    // --- Validation Hook -------------------------------------------------
    /// <summary>
    /// Implement this partial method to add cross-property validation logic.
    /// Set <paramref name="error"/> to a non-default <see cref="PrimitiveError"/> to indicate failure.
    /// </summary>
    static partial void Validate(ref NestedPrimitive value, ref global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError error);

    // --- Factory Methods --------------------------------------------------

    // --- Formatting (IFormattable, ISpanFormattable) ----------------------

    /// <summary>Returns a human-readable representation of this value object.</summary>
    public override string ToString()
    {
        return "NestedPrimitive { }";
    }

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => ToString();

    /// <inheritdoc/>
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        var str = ToString();
        var span = str.AsSpan();
        if (span.TryCopyTo(destination))
        {
            charsWritten = span.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    // --- TypeConverter (ASP.NET / WinForms model binding) -----------------

    private sealed class NestedPrimitiveTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s)
            {
                try
                {
                    return global::System.Text.Json.JsonSerializer.Deserialize<NestedPrimitive>(s);
                }
                catch (global::System.Text.Json.JsonException)
                {
                    return base.ConvertFrom(context, culture, value);
                }
            }
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type? destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType)
        {
            if (value is NestedPrimitive vo && destinationType == typeof(string))
            {
                return vo.ToString();
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // --- JSON Serialization -----------------------------------------------

    private sealed class NestedPrimitiveJsonConverter : global::System.Text.Json.Serialization.JsonConverter<NestedPrimitive>
    {
        public override NestedPrimitive Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            var obj = global::System.Text.Json.JsonSerializer.Deserialize<NestedPrimitive>(ref reader, options);
            return obj;
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, NestedPrimitive value, global::System.Text.Json.JsonSerializerOptions options)
        {
            global::System.Text.Json.JsonSerializer.Serialize(writer, value, options);
        }
    }

}
