//HintName: NestedPrimitive.g.cs
// <auto-generated/>
// Tool: EricksonLopez.DomainPrimitives.Generators
#nullable enable

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using EricksonLopez.DomainPrimitives;
using EricksonLopez.DomainPrimitives.Validation;

namespace TestNamespace;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Text.Json.Serialization.JsonConverter(typeof(NestedPrimitiveJsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof(NestedPrimitiveTypeConverter))]
[global::System.Diagnostics.DebuggerDisplay("{NestedPrimitive}({IsDefault ? \"<default>\" : ToString()})")]
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public readonly partial record struct NestedPrimitive :
    IDomainPrimitive<NestedPrimitive>,
    IParsable<NestedPrimitive>,
    ISpanParsable<NestedPrimitive>,
    #if NET8_0_OR_GREATER
    IUtf8SpanParsable<NestedPrimitive>,
    #endif
    IFormattable,
    ISpanFormattable,
    #if NET8_0_OR_GREATER
    IUtf8SpanFormattable,
    #endif
    System.Numerics.IEqualityOperators<NestedPrimitive, NestedPrimitive, bool>
{
    /// <summary>Returns true if this instance was created via default(T) rather than via Create().</summary>
    public bool IsDefault => true;

    #if NET7_0_OR_GREATER
    /// <inheritdoc/>
    public static string PrimitiveName => "NestedPrimitive";
    #endif

    /// <summary>Canonical error codes for this value object.</summary>
    public static class Errors
    {
        /// <summary>Error code for null input.</summary>
        public const string NullInput = "NULL_INPUT";
        /// <summary>Error code for invariant violation (cross-property validation failure).</summary>
        public const string Invariant = "INVARIANT";
    }

    // ─── Validation Hook ─────────────────────────────────────────────────
    /// <summary>
    /// Implement this partial method to add cross-property validation logic.
    /// Set <paramref name="error"/> to a non-default <see cref="PrimitiveError"/> to indicate failure.
    /// </summary>
    static partial void Validate(ref NestedPrimitive value, ref global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError error);

    // ─── Factory Methods ──────────────────────────────────────────────────

    // ─── Parsing (IParsable, ISpanParsable, IUtf8SpanParsable) ───────

    public static NestedPrimitive Parse(string s) => Parse(s, null);
    public static NestedPrimitive Parse(string s, IFormatProvider? provider)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException($"The value '{s}' is not valid for NestedPrimitive.");
    }

    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (string.IsNullOrWhiteSpace(s))
        {
            result = default;
            return false;
        }
        try
        {
            var obj = global::System.Text.Json.JsonSerializer.Deserialize<NestedPrimitive>(s);
            var err = global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
            Validate(ref obj, ref err);
            if (err.IsError)
            {
                result = default;
                return false;
            }
            result = obj;
            return true;
        }
        catch
        {
            result = default;
            return false;
        }
    }

    public static NestedPrimitive Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
    {
        if (TryParse(s, provider, out var result)) return result;
        throw new System.FormatException("The span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (s.IsEmpty || s.IsWhiteSpace())
        {
            result = default;
            return false;
        }
        return TryParse(s.ToString(), provider, out result);
    }

    #if NET8_0_OR_GREATER
    public static NestedPrimitive Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider = null)
    {
        if (TryParse(utf8Text, provider, out var result)) return result;
        throw new System.FormatException("The UTF-8 span value is not valid.");
    }

    public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out NestedPrimitive result)
    {
        if (utf8Text.IsEmpty)
        {
            result = default;
            return false;
        }
        try
        {
            var obj = global::System.Text.Json.JsonSerializer.Deserialize<NestedPrimitive>(utf8Text);
            var err = global::EricksonLopez.DomainPrimitives.Validation.PrimitiveError.None;
            Validate(ref obj, ref err);
            if (err.IsError)
            {
                result = default;
                return false;
            }
            result = obj;
            return true;
        }
        catch
        {
            result = default;
            return false;
        }
    }
    #endif

    // ─── Formatting (IFormattable, ISpanFormattable, IUtf8SpanFormattable) ───

    /// <summary>Returns a human-readable representation of this value object.</summary>
    public override string ToString()
    {
        return "NestedPrimitive { }";
    }

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => ToString();

    /// <inheritdoc/>
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        var str = ToString();
        var span = str.AsSpan();
        if (span.TryCopyTo(destination))
        {
            charsWritten = span.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }

    #if NET8_0_OR_GREATER
    /// <inheritdoc/>
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)
    {
        var str = ToString();
        return global::System.Text.Encoding.UTF8.TryGetBytes(str.AsSpan(), utf8Destination, out bytesWritten);
    }
    #endif

    // ─── TypeConverter (ASP.NET / WinForms model binding) ─────────────────

    private sealed class NestedPrimitiveTypeConverter : global::System.ComponentModel.TypeConverter
    {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)
        {
            if (value is string s)
            {
                try
                {
                    return global::System.Text.Json.JsonSerializer.Deserialize<NestedPrimitive>(s);
                }
                catch (global::System.Text.Json.JsonException)
                {
                    return base.ConvertFrom(context, culture, value);
                }
            }
            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type? destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType)
        {
            if (value is NestedPrimitive vo && destinationType == typeof(string))
            {
                return vo.ToString();
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }

    // ─── JSON Serialization ───────────────────────────────────────────────

    private sealed class NestedPrimitiveJsonConverter : global::System.Text.Json.Serialization.JsonConverter<NestedPrimitive>
    {
        public override NestedPrimitive Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null)
                return default;
            if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)
                throw new global::System.Text.Json.JsonException("Expected StartObject token for NestedPrimitive.");

            while (reader.Read())
            {
                if (reader.TokenType == global::System.Text.Json.JsonTokenType.EndObject)
                    break;
                if (reader.TokenType != global::System.Text.Json.JsonTokenType.PropertyName)
                    throw new global::System.Text.Json.JsonException("Expected PropertyName token.");

                var propName = reader.GetString();
                reader.Read();

            }

            return default;
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, NestedPrimitive value, global::System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            writer.WriteEndObject();
        }
    }

}
